### ISSUE TITLE
Pass basket line to Range method contains_product

### ISSUE THREAD

**Issue by vovanbo** [django-oscar/django-oscar#1054]
Which reason for passing to Range method `contains_product` only product instance, but not entire basket line, in `can_apply_condition` method of Condition class [here](https://github.com/tangentlabs/django-oscar/blob/master/oscar/apps/offer/models.py#L505)?

``` python
...
product = line.product
return self.range.contains_product(product) and product.is_discountable
...
```

I understand what I can override any method in nested classes of Condition etc. But why it is by default? If reason is Range instance as object of real world is entity what operate not basket lines but products, then I have one example where having of basket line instance in `contains_product` is needed.
1. One table with quantity -> price values and FK to Product. For bulk discount with price by quantity of product rules.
2. On each request basket middleware fetch related objects of basket line.
3. Good place to fetch information about matched rule of price and quantity for current product in basket line is Basket's method `all_lines`.
4. Make own Basket and BasketLine class. Add field `price_by_quantity_rule` to BasketLine which is FK to table from 1 above. Override in Basket following methods – `all_lines` (fetch additional related fields), `add_product` (add related rule in `get_or_create` for new basket line to our table).
5. It's ready for calculate price in my custom Condition and Benefit, all needed information already in basket line without additional queries. But when we calculate range for these discount we need some cycling queries for each product in basket, just because of absent information about basket line.

I am sure it is just one of many examples where this obvious restriction is not good.

**Comment by sasha0** [comment]
I'm not aware of the design decision behind that, but from what I can judge myself, it does make sense to pass the product, but not basket line, since Range model has relations only to Product and by default does not have any logic to operate with line quantity etc.

Conditional offer, condition and benefit model already uses basket to evaluate condition and apply benefits, which should has been enough to check whether the rule is matched, considering price and quantity (item 3).

 `can_apply_condition` method of `Condition` model already accepts basket line and taking into account case described above is quite custom, so I believe current range model implementation should has been sufficient for now.
