### ISSUE TITLE
Managment command for generating an dashboard app skeleton

### ISSUE THREAD

**Issue by izidormatusov** [django-oscar/django-oscar#1153]
When working on a project, custom app has usually its own dashboard app. Dashboard app has quite many boilerplate:
- create views.py with very simple views for each model: ListView, CreateView, UpdateView, DeleteView
- create app.py with those views
- create 3 templates per model: listing, form and delete template

It involves lot of copy-paste, making sure small bits are correct (think breadcrumbs, titles).

This process can be nicely automated.

Let's create a management command that
- accepts application name
- loads models from the application
- generate both initial python modules and templates on correct places
- refuses to generate app if there already exists the dashboard app

**Comment by sasha0** [comment]
Basically could safe time during typical custom dashboard app implementation. Although it's not clear what it would put into the generated python modules - CRUD views for each application models based on Django generic CBV and model forms?

**Comment by sasha0** [comment]
The dashboard is not only set of generic views for CRUD within the templates, but may contain more complex logic.

Hence, I believe it should be enough pre-defined `app.py`, `config.py` and empty `views.py` module in order to initiate dashboard application structure. Perhaps, we may also create template folder and copy sample index.html layout.
