### ISSUE TITLE
Add an AJAX add-to-basket view

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#1352]
Re https://groups.google.com/d/msgid/django-oscar/e27dc156-bb51-4193-8820-cd32ddd08114%40googlegroups.com

We should allow the add-to-basket button on browsing views to use AJAX. This will require a JS snippet and a new view to handle the request.

**Comment by sasha0** [comment]
I'm unsure if this still needs to be implemented in the core, since `django-oscar-api` already perfectly solves it. Either way, it also needs proper client-side implementation and I very much doubt jQuery still good for it, considering plenty of other solutions for this nowadays (React, VueJS etc).

I personally use `django-oscar-api`, JS framework may vary from project to project, so I would appreciate other opinions regarding this. Thanks.

**Comment by specialunderwear** [comment]
You need https://django-oscar-api.readthedocs.io/en/latest/usage/middleware.html#basket-middleware to make the api views share session with the standard views. Also oscarapi does away with the cookie basket entirely. So it is rather a matter of taste if you want to add so many dependencies to just add an ajax basket. I think all this depends on how many people really use oscar's builtin views as they come out of the box. (I've never used them :-). Could still be worthwile to have in core I guess.

If not it is rather trivial to add an ajax basket with oscarapi if you use the middleware mentioned above.

**Comment by inopia** [comment]
I use `django-oscar-api` for that and think that this issue should be closed. 

I don't think it's worth duplicating the effort between it and oscar core.

**Comment by pwalsh** [comment]
I think it does not need to be implemented in core.

**Comment by craigloftus** [comment]
We use `django-oscar-api` as well. I'm going to close this, as that seems to be the consensus.

I'm less sure it doesn't belong in core in the long term, but that needs to be part of the bigger conversation about the scope of `django-oscar` generally.
