### ISSUE TITLE
Make Oscar agnostic of thumbnailing solution

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#1408]
Oscar really shouldn't care how thumbnails are generated. It [leads to trouble](https://groups.google.com/d/msgid/django-oscar/673527cf-81f6-4901-9176-279992454ae3%40googlegroups.com?utm_medium=email&utm_source=footer) when integrating e.g. django CMS as they use `easy-thumbnails`. There's also solutions like [thumbor](https://github.com/thumbor/thumbor) and [resrc.it](http://www.resrc.it/) better suited for handling thumbnails when using remote storages like S3.

I'm imagining a backend-agnostic `oscar_thumb` template tag that is easy to customise. 
As far as I'm aware, the only advanced usage of the `thumbnail` tag is `crop=centre` for the gallery thumbs, which surely could be made to work somehow.

Questions remaining:
- [ ] Should we drop Sorl as a required dependency? That means PIL wouldn't get installed by default, which makes the final environment lighter. But it probably doesn't provide for a good out-of-the-box experience.

**Comment by creimers** [comment]
@uKev Can I contact you about your djangoCMS - Oscar integration experience? If so, how?

**Comment by maikhoepfel** [comment]
Please do! m@maikhoepfel.de.

**Comment by maikhoepfel** [comment]
Pinging @JostCrow because he's working on this. \o/

**Comment by sasha0** [comment]
Looks like @JostCrow already did some implementation, but not sure if that was finished. Looking forward to see it!

**Comment by JostCrow** [comment]
Sorry for the late response. It has been a little bit busy.

I am still working on a good solution. I have indeed started on creating a solution. Feel free to give any feedback if you have some.

**Comment by alfaro28** [comment]
Any updates on this issue?, I recently had trouble because my project was already using easy_thumbnails

**Comment by Bogh** [comment]
:+1:

**Comment by Bogh** [comment]
I've looked over @JostCrow implementation and I think it's not a good idea to duplicate the templates. Give that there are quite a few. I was thinking a template tag that returns the thumbnail of the image and wraps both libraries and any future that wants to be used. 

Allowing for a setting that will specify the THUMBNAIL_FUNCTION to be called and create and return the thumb of the image.

I will start working in this direction and I'm open to suggestions.

**Comment by sephii** [comment]
@Bogh any update on this? Have you seen this issue? https://github.com/mariocesar/sorl-thumbnail/issues/480

**Comment by sephii** [comment]
I started working on this here https://github.com/liip-forks/django-oscar/tree/agnostic-thumbnails

**Comment by sasha0** [comment]
@sephii great job on thumbnails refactoring. Would you create a PR so we can review? Thanks!

**Comment by sasha0** [comment]
Also, in terms of this issue it needs to rework signal receiver for thumbnails cleanup, which is also tight to `sorl-thumbnails` now.

**Comment by sasha0** [comment]
Me and @samitnuk took time to revise it again and came up with next conclusions:
- If we aim to make it really agnostic, we'd not provide any default thumbnail backend set by default, so that users can make a choice by themselves, even though we'd provide ready-made backends for sorl and easy-thumbnails. In this case there won't be unnecessary dependency if users decide to implement thumbnail backend by themselves or integrate something other that two listed above backends. Hence, sorl won't be in the `INSTALLED_APPS` by default.
- We can use the same approach as uses django-haystack or Celery for pluggable backends
  - Install Oscar within the Sorl within the next command - `pip install django-oscar[sorl]` or let user install manually.
  - Implement backends as modules and enable only if related package imports works fine.

Your thoughts @django-oscar/developers ?

**Comment by sasha0** [comment]
We have finally finished this functionality within the PR #2621 and it will be delivered within the Oscar 2.0.
