### ISSUE TITLE
Declare public API so that we can apply Semver rules

### ISSUE THREAD

**Issue by mbertheau** [django-oscar/django-oscar#1575]
I think the consensus is to follow http://semver.org/ for versioning oscar. With the 1.0 release the main semver rules start to apply, and for that we need to follow rule number 1:

> "1. Software using Semantic Versioning MUST declare a public API. This API could be declared in the code itself or exist strictly in documentation. However it is done, it should be precise and comprehensive."

Any suggestions or thoughts on what we should make public API?

**Comment by john-parton** [comment]
Anywhere Oscar says "This is domain specific, you need to implement your own stuff here, we should look closely at any classes or methods that one would have to use to actually finish the implementation.

One example:
`OrderPlacementMixin` requires you to implement `handle_payment`. It's presumed that you will use the other methods on `OrderPlacementMixin` in order to accomplish this.

Many (most? all?) signals should probably be public as well.

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have open PR's attached.
