### ISSUE TITLE
Product class nullable?

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#1633]
A fellow developer saw the [code](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/catalogue/abstract_models.py#L267) for the product - product class relationship and assumed product class can be set to `None`. AFAIK, that is not the case and we rely on it.
I realize why we need to set it to be nullable for the deletion, but that leaves us with products in an awkward state. Is a simple docstring enough?

**Comment by mvantellingen** [comment]
What is actually the reason for the null=True? Since `on_delete` is set to `PROTECT` a product class can never be deleted when it's still in use.

As far as I can see we can remove the `null=True`

**Comment by maikhoepfel** [comment]
That's a good question. I very vaguely remember there's some strangeness with MySQL and not enforcing the ``on_delete`` actions. But I really don't know.

**Comment by john-parton** [comment]
Correct me if I'm wrong, but isn't it simply that children have `product_class=None`?

**Comment by mvantellingen** [comment]
@john-parton yup, you are indeed right :-) Still wondering if that is the correct thing though

**Comment by john-parton** [comment]
I would rather not have to manage the product_class foreign key on both the parent and child, because that introduces the possibility of the parent and child having different product classes, which doesn't really make sense to me.

For instance, if the parent and children have product_class_id == T-Shirt, and then the parent is updated so that product_class == Sweater, then we have to make sure to go and update the product_class for all of the children to be Sweater. If we force children to have a null value, then we don't need to go out of our way to ensure that they match up.

(To use more formal language, having the foreign key relationship be on both models is less normalized than simply having it on the parent.)

**Comment by sasha0** [comment]
Reason of the nullable product class field already shortly documentation in the `Product` model. Totally agree with @john-parton and don't see the reasons to change existing behavior.
