### ISSUE TITLE
Discount tax calculation wrong?

### ISSUE THREAD

**Issue by mbertheau** [django-oscar/django-oscar#1683]
I changed the sandbox to a 20% fixed tax rate, added a 50% site-wide product percentage benefit offer and bought a commandlinefu t-shirt (net 10 €). I get the following tax calculation on the order page:

![image](https://cloud.githubusercontent.com/assets/133575/6394810/605e5ad2-bdd4-11e4-86b4-52bf098a8b49.png)

Now it doesn't look sensible to me that the end result would be 4€ net 6€ gross, because that's 50% tax.

Shouldn't the correct calculation be:
- discount excl tax: 5€
- basket total incl discount excl tax: 5€
- order total excl tax: 5€

That's what's correct for our case. I really know only rumours about the VAT system of countries other than Germany, so I wonder whether that calculation makes sense somewhere in the world.

``` diff
diff --git a/src/oscar/apps/partner/strategy.py b/src/oscar/apps/partner/strategy.py
index ded5c18..398abcd 100644
--- a/src/oscar/apps/partner/strategy.py
+++ b/src/oscar/apps/partner/strategy.py
@@ -263,7 +263,7 @@ class FixedRateTax(object):
     stockrecord.  The price_incl_tax is quantized to two decimal places.
     Rounding behaviour is Decimal's default
     """
-    rate = D('0')  # Subclass and specify the correct rate
+    rate = D('0.2')  # Subclass and specify the correct rate
     exponent = D('0.01')  # Default to two decimal places

     def pricing_policy(self, product, stockrecord):
@@ -322,7 +322,7 @@ class DeferredTax(object):
 # charge tax!


-class Default(UseFirstStockRecord, StockRequired, NoTax, Structured):
+class Default(UseFirstStockRecord, StockRequired, FixedRateTax, Structured):
     """
     Default stock/price strategy that uses the first found stockrecord for a
     product, ensures that stock is available (unless the product class
```

**Comment by mbertheau** [comment]
I get the presumably correct calculation with the below diff, but since getting taxes right can't be trial and error I'd be interested in some feedback, @codeinthehole :)

```diff
diff --git a/src/oscar/apps/offer/models.py b/src/oscar/apps/offer/models.py
index a4f66a5..b3780c3 100644
--- a/src/oscar/apps/offer/models.py
+++ b/src/oscar/apps/offer/models.py
@@ -59,7 +59,7 @@ def apply_discount(line, discount, quantity):
     """
     Apply a given discount to the passed basket
     """
-    line.discount(discount, quantity, incl_tax=False)
+    line.discount(discount, quantity, incl_tax=True)
 
 
 @python_2_unicode_compatible
```

**Comment by sasha0** [comment]
@mbertheau did you change pricing strategy on sandbox site locally?

**Comment by leo-naeka** [comment]
I'm also facing this issue.

Considering a 10% `PercentageDiscountBenefit` offer on a product with a 20% `FixedRateTax`.

1. Discount amount is computed [here](https://github.com/django-oscar/django-oscar/blob/1.1.1/src/oscar/apps/offer/benefits.py#L71-L72), we get `price` from `get_applicable_lines`
2. `get_applicable_lines` retrieves price on `utils.unit_price` ([here](https://github.com/django-oscar/django-oscar/blob/1.1.1/src/oscar/apps/offer/abstract_models.py#L604)), itself using `line.unit_effective_price` ([here](https://github.com/django-oscar/django-oscar/blob/1.1.1/src/oscar/apps/offer/utils.py#L20))
3. `unit_effective_price` get the `effective_price` on `purchase_info.price` and `purchase_info` has the strategy applied ([here](https://github.com/django-oscar/django-oscar/blob/1.1.1/src/oscar/apps/basket/abstract_models.py#L733-L734))
4. Having a strategy based on a `FixedRateTax`, the `TaxInclusiveFixedPrice` is used ([here](https://github.com/django-oscar/django-oscar/blob/1.1.1/src/oscar/apps/partner/strategy.py#L266-L269)) so `effective_price` is **tax included** ([here](https://github.com/django-oscar/django-oscar/blob/1.1.1/src/oscar/apps/partner/prices.py#L96))

That far, everything seems fine, our discounts are based upon tax inclusive prices, that seems in accordance with `TaxInclusiveFixedPrice` pydoc ([here](https://github.com/django-oscar/django-oscar/blob/1.1.1/src/oscar/apps/partner/prices.py#L79-L81)) added in @codeinthehole's commit a737f74 which is precisely related to this "tax in/ex-clusive offer situation".

The fact is I don't get why discount is computed like this:

```python
def apply_discount(line, discount, quantity):
    """
    Apply a given discount to the passed basket
    """
    line.discount(discount, quantity, incl_tax=False)
```
With a forced `incl_tax=False` in `offer.benefits` ([here](https://github.com/django-oscar/django-oscar/blob/1.1.1/src/oscar/apps/offer/benefits.py#L19-L23))

Because of this, the discount amount, computed on the **inclusive price**, is set to the `_discount_excl_tax` attribute of the basket line ([here](https://github.com/django-oscar/django-oscar/blob/1.1.1/src/oscar/apps/basket/abstract_models.py#L646)).
Then, when we check for `line_price_excl_tax_incl_discounts `, the [errored discount amount is returned](https://github.com/django-oscar/django-oscar/blob/1.1.1/src/oscar/apps/basket/abstract_models.py#L765-L767).

Like @mbertheau, I'm not well aware of other countries tax application. Setting `incl_tax=True` in `apply_discount` fix it for my situation but I don't truly realize the implication with other benefit types.

Whatever, there's definitely an issue there: discount amount is computed from an inclusive price and then retained on an exlusive price. This is not related to any country law and sounds like an insidious silent bug which can only work if the tax is deferred and then not taken in account in `unit_effective_price`.

CC @sasha0 @codeinthehole @mbertheau .

**Comment by leo-naeka** [comment]
I've actually tested this a little bit more, and it also affects `AbsoluteDiscountBenefit`, `FixedPriceBenefit` offers.

**Comment by Mohl** [comment]
I also discovered that appearently, the `_discount_excl_tax` property does get set in AbstractLines `discount()`, but the change has to be overwritten somewhere afterwards as the tax calculation does not include the calculated discount. Basically, the voucher gets associated to the basket, but `_discount_excl_tax` returns D('0.00'), which messes up the baskets tax calculation.

I discovered this with a standard 10%-off voucher, as created via the dashboard.
