### ISSUE TITLE
Product attribute's code generated with dashes

### ISSUE THREAD

**Issue by vovanbo** [django-oscar/django-oscar#1713]
Let's see in the following code:
```python
>>> class Tmp(object):
...     pass
...     
>>> tmp = Tmp()
>>> setattr(tmp, 'temp-code', 123)
>>> tmp.temp-code
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'Tmp' object has no attribute 'temp'
>>> tmp.__dict__
{'temp-code': 123}
>>> getattr(tmp, 'temp-code')
123
```
Attribute was set, object have this attribute, but this attribute can not be accessed directly as `tmp.temp-code`. That's right, this is Python.
Product's attributes with spaces in their names have generated code with dashes. So, these attributes can not be accessed with `product.attr.some-attribute`, because of dash in attribute's codename is interpreted as minus sign in program's code. Documentation for `ProductAttributesContainer` offer this way to get attribute's values, but one way to get value is `getattr(product.attr, 'some-attribute')`.
This behavior can be fixed with using AutoSlugField with underscore as separator [here](https://github.com/django-oscar/django-oscar/blob/master/src%2Foscar%2Fapps%2Fcatalogue%2Fabstract_models.py#L780-L785):
```python
class AbstractProductAttribute(models.Model):
    ...
    code = models.SlugField(
        _('Code'), max_length=128,
        validators=[RegexValidator(
            regex=r'^[a-zA-Z\-_][0-9a-zA-Z\-_]*$',
            message=_("Code can only contain the letters a-z, A-Z, digits, "
                      "minus and underscores, and can't start with a digit"))])
    ...
```
Any thoughts?

**Comment by john-parton** [comment]
This isn't a bad idea. I have several places in my code where I have to work around this issue using `getattr` and this approach might save me some headache.

**Comment by maikhoepfel** [comment]
Hi,

good point! But I wouldn't use AutoSlugField because then the attribute
names become unpredictable and often code will rely on them. I'd just add a
validator to the field that ensures we only allow valid characters.

Vladimir or John, do you think you could prep a PR for it? Otherwise,
please create an issue and we'll look at it when time permits.

Cheers,

Maik

**Comment by maikhoepfel** [comment]
Whoops, just saw this is already an issue. Ignore that paragraph. A PR is still welcome :)

**Comment by john-parton** [comment]
Submitted a PR.

There's only one tiny issue. If you supply a name with spaces, the `prepopulated_fields` javascript generates a code with hyphens, which then fails validation. I'm inclined to leave it as is. The code is still correct when there are no spaces, and having users manually tweak the code shouldn't be that big of a deal, especially because `ProductAttributes` are rarely created.

**Comment by mvantellingen** [comment]
Cool, thanks for the PR. Perhaps in the future it might be a good idea to create an AttributeNameField() to make it more re-usable?

**Comment by john-parton** [comment]
Is there another place a field like this is used? If so, I can add that field and refactor. If not, I'm inclined to leave it as-is.

Thanks,
John

**Comment by mvantellingen** [comment]
@john-parton , I was thinking about AbstractPartner.code. But I'm now thinking this should stay as-is.

**Comment by mvantellingen** [comment]
Found another one: https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/customer/abstract_models.py#L141

See #1653

So a generic AttributeNameField does feel like the correct approach to me.

**Comment by john-parton** [comment]
"AttributeNameField" feels kind of vague. Maybe PythonIdentifierField? With
a PythonIdentiferValidator that subclasses RegexValidator?

Found another one:
https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/customer/abstract_models.py#L141

See #1653 <https://github.com/django-oscar/django-oscar/issues/1653>

So a generic AttributeNameField does feel like the correct approach to me.

—
Reply to this email directly or view it on GitHub
<https://github.com/django-oscar/django-oscar/issues/1713#issuecomment-100544075>
.

**Comment by vovanbo** [comment]
I'm not sure about AutoSlugField implementation, but why it can be used [here](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/catalogue/abstract_models.py#L1090-L1091), for example:

```python
...
class AbstractOption(models.Model):
    name = models.CharField(_("Name"), max_length=128)
    code = AutoSlugField(_("Code"), max_length=128, unique=True,
                         populate_from='name')
...
```

and can't be used as fix for this issue?

**Comment by john-parton** [comment]
I think there's a related issue. If you set the code to be a python keyword , you can't access the attribute directly because `product.attr.import` will raise a `SyntaxError`.

I'm not sure if anyone has actually encountered that issue, but it would be relatively trivial to include a check with `keyword.iskeyword` https://docs.python.org/2/library/keyword.html

**Comment by mvantellingen** [comment]
I've just looked how this is done in the namedtuple() code:

```python
        if type(name) != str:                                                      
            raise TypeError('Type names and field names must be strings')          
        if not all(c.isalnum() or c=='_' for c in name):                           
            raise ValueError('Type names and field names can only contain '        
                             'alphanumeric characters and underscores: %r' % name)
        if _iskeyword(name):                                                       
            raise ValueError('Type names and field names cannot be a '             
                             'keyword: %r' % name)                                 
        if name[0].isdigit():                                                      
            raise ValueError('Type names and field names cannot start with '       
                             'a number: %r' % name)  
```

**Comment by john-parton** [comment]
That's interesting. The first part isn't really needed because the `CharField` validation will catch it. The 2nd and 4th parts are equivalent to the regex. The 3rd part is important because keywords are invalid attributes.
Obviously we would raise `ValidationError` instead of `ValueError`.

I have a basic validator that I outlined here: https://github.com/django-oscar/django-oscar/pull/1729#issuecomment-105995612
