### ISSUE TITLE
Question: Simple Checkout without multiple steps

### ISSUE THREAD

**Issue by steffenmllr** [django-oscar/django-oscar#1725]
I'm evaluation django oscar for a project atm and looking at how hard it would be to customize the checkout to one (ajax) request (No signup). 

So far it seems like the checkout requires multiple stages and redirects and I found #1678 which seems something in that direction.

Therefore my question: How hard is it at the moment to create a whole order from scratch within one request ? Is this even possible or do I have to use multiple steps ?

If it is possible, could someone please point me in the right direction one how this could be done ?

thanks

**Comment by mbertheau** [comment]
Hi @steffenmllr,

With released versions of oscar you'd have to copy together code from a number of places to create an order. So it's possible, but only because oscar is open source :)

We're using this branch https://github.com/machtfit/django-oscar/tree/machtfit right now, and we have a one-step checkout process. However, we do require signing in and we have no basket functionality (only one product, quantity always 1).

I do hope to get all of his into oscar proper, but only time will tell whether that'll happen.

HTH

Markus

P.S. feel free to reopen if you have further questions.

**Comment by mvantellingen** [comment]
Additionally, take a look at https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/order/utils.py#L38 

This class is responsible for creating the final order, so if you collect the required info on some other way (remember it's all just Django) and you pass them to this method then all will be fine :-)
