### ISSUE TITLE
Frozen Basket after returning back from paypal checkout

### ISSUE THREAD

**Issue by jlmadurga** [django-oscar/django-oscar#1734]
When a user goes back(no cancelling) from a third party payment the basket stays as frozen.
I have just solved recovering (thaw) frozen basket if user has one.

Is there any collateral issues with this behavior?  i.e. user enters from another browser when paying so baskets is not frozen anymore?

It is a pain for the user to lose the basket if regrets to make the payment.

**Comment by mbertheau** [comment]
The point of freezing the basket is that during payment no other items can be added to it. Otherwise you could initiate payment, add some more items to your basket, finish the payment and have an order that costs more than you paid.

What you should do instead is create a new basket if the current basket is frozen and put all the products from the frozen basket in the new basket as well. This gets problematic if you track stock - then you need a notion of reserving items for some time for checkout. Oscar doesn't implement that fully

**Comment by jlmadurga** [comment]
You are right. It is quite dangerous to thaw the basket it is better to created a new one merging content. 

But I don't get the tracking problem. Imagine:
* Checking out basket (A= Value 10) set to frozen
* User opens new browser Basket B is merged with content A (Value = 10) 
* Before completing checkout Basket B adds new content trying to pay less for more
* Completing the checking out of Basket A fails because the frozen basket is in merged state.

**Comment by mbertheau** [comment]
@jlmadurga Well, for one thing, oscar doesn't have a built-in way of reversing the payment, so even if the checkout fails, you still have to solve the problem of returning the money to the customer.

But what I meant is not for the baskets to be merged, but for basket B to have all products from basket A added to it. The stock tracking problem is actually a separate issue, sorry for confusing that here.
