### ISSUE TITLE
No support for multi-valued ProductAttributeValue 

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1739]
There's this PR which attempts to resolve this issue: https://github.com/django-oscar/django-oscar/pull/879

I'm not sure it's the "best" way of fixing this, but I think we should have a way of making this work.

Right now, as a workaround, I'm just using a text field and entering in values comma-separated, which works OK, but obviously is somewhat brittle.

I might submit a PR here with a different solution.

Thanks,

John

**Comment by anentropic** [comment]
I have same issue.

Currently there is support for multi-valued option in `apps.dashboard.catalogue.forms`... I started trying to implement it...

I can remove the `unique_together` from `AbstractProductAttributeValue` with an extended class (obviously the model then ought to have further validation, which looks like will be handled by #879)

But I can't add the `MULTI_OPTION` choice to `TYPE_CHOICES` on the `AbstractProductAttribute` model by extending it, because I would have to redefine the existing field.

As a minimal change I would like to see the `MULTI_OPTION` added to `TYPE_CHOICES` asap even if the proper validation etc is not in place, so we are not blocked from hacking up something for ourselves in the meantime.

**Comment by john-parton** [comment]
Thanks for your input.

I think you're 100% right that we should at least add a `MULTI_OPTION` choice to `TYPE_CHOICES` because an application developer simply cannot modify it currently.

However, if it is possible to include a partially- or fully-featured implementation, we should do so.

**Comment by john-parton** [comment]
I updated the changes as discussed in https://github.com/django-oscar/django-oscar/pull/1745#issuecomment-106035074

This seems like more reasonable behavior.

Also amended the commit so that I'm the author (was showing @codeinthehole as the author after I did the rebase) and squashed it into a single commit.

There are still no tests, but I would really appreciate some input before continuing.

**Comment by solarissmoke** [comment]
Fixed in #2309.
