### ISSUE TITLE
FixedRateTax.pricing_policy vs parent_pricing_policy discrepancy

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1855]
I'm trying to write some addition tests for `oscar.apps.partner.strategy.FixedRateTax`, but I've hit a stumbling block:

Why does `FixedRateTax.pricing_policy` return an instance of `prices.TaxInclusiveFixedPrice`, but `FixedRateTax.parent_pricing_policy` return an instance of `prices.FixedPrice`?

If the rate is non-zero, this creates a scenario where `strategy.pricing_policy().effective_price != strategy.parent_pricing_policy().effective_price`.

**Comment by sasha0** [comment]
Since `FixedRateTax` supposed to apply tax to base price, I assume we could wrap `FixedRateTax.parent_pricing_policy` with `prices.TaxInclusiveFixedPrice` for consistency. Also this ideas is proved my `DeferredTax` strategy implementation - it's not intended to apply tax immediately, so that it uses `prices.FixedPrice` which does not include tax to effective_price.
What do you think?

**Comment by john-parton** [comment]
I'm still not sure what the difference is between `prices.TaxInclusiveFixedPrice` and `prices.FixedPrice`. Can you give me an example use-case for each one?

Thanks.

**Comment by sasha0** [comment]
The difference between `effective_price` property - for `FixedPrice` it's tax-exclusive, for `TaxInclusiveFixedPrice` it's tax-inclusive price, respectively. Examples: for `TaxInclusiveFixedPrice` - UK prices, for `FixedPrice` - US prices.

**Comment by sasha0** [comment]
Initial question seems to be clarified by the latest comment. Feel free to re-open in case of other questions/issues. Thanks!
