### ISSUE TITLE
Formsets are hard to override

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#1957]
For instance, it's [hard to override](https://groups.google.com/forum/?fromgroups#!searchin/django-oscar/stockrecord$20form/django-oscar/sW7t_Y_b8GE/Yh8dswl1IL0J) the dashboard's `StockRecordForm`. If one wants to add or remove a field, one has to inherit the field, but also copy across `StockRecordFormSet`. 
Most likely, we want to move all of Oscar's formsets into `formsets` modules, and dynamically load the related forms.

**Comment by maxshilov** [comment]
hello Maik,

Could you please explain why get_class solution would't work in this case?

**Comment by Mohl** [comment]
@maikhoepfel is right. I just added a field to StockRecord. To expose that field to the dashboard, one has to do the following:

Override the StockRecordForm (thats obvious)
Override the BaseStockRecordFormSet (it's not using get_class, because the two classes are in the same file)
copy the whole StockRecordFormSet to the own catalogue/forms.py (yes, hardcopy. this adds 64 lines to your project that you are now responsible for).
override the ProductCreateUpdateView and manually set it's formset dict to the StockRecordFormSet you just copied.
override the dashboard/catalogue/product_update.html template and manually add the new StockRecord field (basically, two lines) to the 343 long template, which is now also under your responsibility.

Aka, you have to spend 2 hours on a 15 Minute job.

**Comment by sasha0** [comment]
@maikhoepfel how about backward compatibility?
