### ISSUE TITLE
manage.py command for populating recommended products

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#20]
Write a `manage.py` command that populates the product recommendation models
based on the data within order history.  Just follow the rules for "customers who
bought x, bought y"

Create a service that takes in a basket, and returns the a set of recommended products

**Comment by john-parton** [comment]
I will be implementing this feature in an upcoming project, does anyone have a partially working implementation?

**Comment by john-parton** [comment]
For anyone reading this, I ended up using elastic's "more like this" functionality to dynamically generate recommended products. The overall fidelity of recommendations might be less than manually specified products, but the dramatic reduction in data entry burden was considered a reasonable trade off for my application.

**Comment by sasha0** [comment]
I believe within just simple lookup in the order history we can't get relevant products, because customers often buy unrelated products in the same order. To get list of similar products, we'll have to design quite more complex algorithm, which is potential topic for the new issue we'd create once we get to implement this.
