### ISSUE TITLE
Partners can view and edit the status of each others orders 

### ISSUE THREAD

**Issue by cmwaura** [django-oscar/django-oscar#2240]
I was going through the process and i came across what might be a bug that i wanted a second opinion on.

Assuming a customer places an order consisting of X(belongs to partner X) and Y (belong to partner Y). Once the order is confirmed and processed, the order shows up at the dashboard of both partners. However, partner X can see and edit partner Y's orders and vice versa. I thought this was a problem with the version that I had of oscar but when i updated to the latest version, the same thing occurs. Is this supposed to happen?

**Comment by solarissmoke** [comment]
Yes - this is expected behaviour. A Partner will be able to see the full details of any order that has a line that belongs to them. 

If you need this functionality you are probably better off writing a separate view based on `dashboard.order.OrderDetailView` that renders the order in the way you want.
