### ISSUE TITLE
Make PurchaseInfo a proper class that can be overridden in the same way as other classes

### ISSUE THREAD

**Issue by boosh** [django-oscar/django-oscar#2399]
I need to add extra methods to the `PurchaseInfo` class, but because it's defined and used directly in `apps/partner/strategy.py` I can't without duplicating that whole file.

It'd be helpful if `apps/partner/strategy.py` was changed to attempt loading that class using `get_class` and falling back to the current default if it's not been overridden somewhere else.

**Comment by boosh** [comment]
I needed to add a method `any_available_to_buy` that would return `True` if the product or any variants were available to buy. This is used in templates to conditionally show the basket or let users sign up for alerts if nothing can be bought.

**Comment by solarissmoke** [comment]
> I needed to add a method any_available_to_buy that would return True if the product or any variants were available to buy.

This is something that would typically be done in the `Strategy` and `Selector` classes (both of which can be overridden), which are responsible for determining whether a product or variants is available to buy or not, and the price information.

The `PurchaseInfo` tuple is intended to be a very lightweight container for holding the results of a strategy (price, availability, stock record) rather than for performing any logic.

Is there a reason why you can't do this logic in a custom `Strategy` class?

**Comment by boosh** [comment]
Oh right, I hadn't seen that the strategy instance was available as `request.strategy`.  Is that always the case? If it is I can probably move my code into my strategy. I'll try and get back to you.

**Comment by solarissmoke** [comment]
Yes, the `BasketMiddleware` sets `request.strategy` for all requests.

**Comment by solarissmoke** [comment]
Closing as it seems that the `Strategy` class should let you achieve what you want. Feel free to reopen if you still think there's a use case that isn't being met.
