### ISSUE TITLE
Forking Core Files of Oscar for Customisation

### ISSUE THREAD

**Issue by artforlife** [django-oscar/django-oscar#2442]
Having read the part of documentation that describes forking an application to prepare for its customisation, I am wondering if there is a way to fork files located inside the `oscar/` directory. For instance, one file of interest is `oscar/default.py` that contains definition of the Dashboard menu. 

Obviously, whenever there is an update in the version of Oscar, it gets overridden.

Is there a way to fork this in version 1.5?

**Comment by SalahAdDin** [comment]
@artforlife Afaik `open-edx` fork many applications over `django-oscar`, if you want you can see his project and review it.

**Comment by artforlife** [comment]
What exactly do you mean?

**Comment by SalahAdDin** [comment]
you can use his project like a recipe if you need.

**Comment by solarissmoke** [comment]
It's not clear what you're asking here. `oscar/defaults.py` are just default settings which you can override in your project's settings file (this is described in the [documentation](http://django-oscar.readthedocs.io/en/releases-1.5/internals/getting_started.html#django-settings).

Everything else in Oscar - views, classes - can be overridden as well using the methods described in the documentation.

Also, please use the mailing list for support questions, rather than the github issue tracker which is for bugs and issues in the code base. Thanks!

**Comment by solarissmoke** [comment]
Closing as this appears to be a setup question. Feel free to ask for help on the support forum.
