### ISSUE TITLE
Missing products in Product Category

### ISSUE THREAD

**Issue by D-Jet** [django-oscar/django-oscar#2445]
I switching Haystack's backend to ElasticSearch and all works fine. But there is one problem.

When new product added you must run the command `./manage.py update_index` to inform Haystack update search indexes.

Haystack have RealtimeSignalProcessor that used for updating index every time when models saved/deleted.
With this SignalProcessor Haystack proper well.

After creating Product I check: 
```bash
./manage.py shell
```
```python
from haystack.query import SearchQuerySet
sqs = SearchQuerySet().all()
sqs.count() # shows the correct result
```
And if I use Search I get the correct results.

But if I open any Category the newly created product does not appear in the product list.
If I add some facets to search (for example, the price), they will show that the product has appeared. But in the list it is still missing.

Product appears in product list only in two ways:
1. Using the command `./manage.py update_index`
2. Saving newly created Product TWICE.

Here my Haystack settings:
```python
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
        'URL': 'http://127.0.0.1:9200/',
        'INDEX_NAME': 'haystack',
    },
}

HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
```
Package versions that I use:
django 1.10.5
django-oscar 1.4
haystack 2.5.x-2.6.x

ElasticSearch 1.7.6

Is there any way to fix this problem? Or the only option is to use asynchronous tasks?

**Comment by sasha0** [comment]
Sorry for long response. 

So please clarify - with `RealtimeSignalProcessor` product immediately appears in the product list after creation, but do not appear on category page? Thanks.

**Comment by sasha0** [comment]
Alright, I've figured it out.

`RealtimeSignalProcessor` is called by `post_save` database signal of the model. Thus, when we save `Product` model it's being updated in the search index.

When we save product in the dashboard, we firstly save product form and after that - all formsets, including category formset. Thus, categories being saved _after_ product and at the moment of the `RealtimeSignalProcessor` call product does not have categories assigned, which is basically the reason of product not being displayed on the category products list.

In order to get product updated in the search index within all related fields, you can trigger search index record update in `ProductUpdate.forms_valid` method. Oscar lets to make decision how to handle search index update by the user and does not integrate or implement signals to invalidate search index records.

In the future we intend to implement custom Elasticsearch wrapper, which @solarissmoke and @craigloftus already working on.
