### ISSUE TITLE
[Issue] Child Product Description in Basket and Order  ver 1.5

### ISSUE THREAD

**Issue by mykljohn** [django-oscar/django-oscar#2474]
I think there is an error with this.  It only displays the Child Title and not the Parent Title so for example Parent T-Shirt, Child Red, it only displays Red in basket/basket_quick.html, basket_content_html, checkout/checkout-html, thank_you.html, customer/order/order_details.html, emails/commtype_order_placed_body.html.  

I changed it to {{ line.product.parent.get_title }} - {{ line.description }}

**Comment by solarissmoke** [comment]
This expected behaviour. Oscar assumes that if you set a title on the child product, then it replaces the title of the parent product - see https://django-oscar.readthedocs.io/en/releases-1.5/ref/apps/catalogue.html#oscar.apps.catalogue.abstract_models.AbstractProduct.get_title 

Oscar does not concatenate child title with the parent title - and I think this would be confusing if it did.

**Comment by mykljohn** [comment]
Ahh, so how do you get the description of the Parent to show when there are children as in my example?

**Comment by solarissmoke** [comment]
You can fetch `product.parent.title` if you need to display it in your own templates.

**Comment by solarissmoke** [comment]
As noted above this is expected behaviour which you can adjust in your project.
