### ISSUE TITLE
New search backend

### ISSUE THREAD

**Issue by sasha0** [django-oscar/django-oscar#2539]
The basic idea is to replace `django-haystack` entirely with the custom implementation on top of Elasticsearch.

**Comment by SalahAdDin** [comment]
@sasha0, it could be very hard, `wagtail` have his own backend for `elasticsearch`, but i don't know how much hard is it.

**Comment by pwalsh** [comment]
Could help https://github.com/sabricot/django-elasticsearch-dsl

**Comment by digicase** [comment]
I know @john-parton wrote a custom search backend based on Elasticsearch DSL, as he mentioned it either in the issues here or the Oscar mailing list. I'm not sure how active John is now with Oscar, but it may be worth a search to see what he wrote and any pointers he gave.

**Comment by john-parton** [comment]
@digicase I did, and then I rewrote it to use `elasticsearch-py` directly. I implemented product variants as a nested element in the product search index. Also implemented MLT functionality, search auto-complete, and search suggestions. (Auto complete and suggestions are of course based on the actual text that's fed in, so it's specific to the catalog.) Faceting is still in progress, though it works well enough. 

I even have some really advanced features where I use `inner_hits` to rank a variant so that I can select the most appropriate image for a variant, and then pass the variant id to the product page as a hash-fragment, so that the product page can show the right variant.

Performance is pretty tight, because I passed everything I might need about the product directly to elastic. *Zero* database queries are performed with a typical search.

All of that was cumbersome to maintain with `elasticsearch-dsl`, unfortunately. 

I think the absolute most difficult thing will be writing the search app in such a way that Oscar users can customize it. The biggest down side to mine is that I hard-coded tons of stuff that was specific to my app.

**Comment by solarissmoke** [comment]
WIP PR is here:  #2606

**Comment by 42force** [comment]
Hi =, can you still use solr, or it is advisable to use django-elasticsearch-dsl?

**Comment by capelito** [comment]
Hi, @specialunderwear made the effort and prepared https://github.com/specialunderwear/django-oscar-elasticsearch as a new search backend. I would like to help ( https://github.com/django-oscar/django-oscar/pull/2734#issuecomment-508467148 ) to integrate it in django-oscar. Is django-oscar-elasticsearch a candidate to become the default search backend or do the core maintainers have other plans? Thank you.

**Comment by solarissmoke** [comment]
@capelito very happy to make ES the default search backend, and would be very grateful if you are be able to spend the time to make a PR to integrate this into Oscar. Happy to review/test.

**Comment by Eslam-Elkobia** [comment]
Hi @solarissmoke, is this feature moved to 2.2 milestone?

**Comment by specialunderwear** [comment]
The Elasticsearch search backend will not be integrated into oscar, because it depends on wagtail.
Also we currently think that it is much to difficult to modify and customize.
We are working on a new implementation for elasticsearch, which should be ready by the end of the year. We will make it feature complete with [django-oscar-elasticsearch](https://github.com/specialunderwear/django-oscar-elasticsearch)  and test it for a while, then we will integrate it into oscar if all is well.
We don;t need to track the progress with this ticket, so I'm closing it since:

closing all issues that are feature requests without open PR's attached.
