### ISSUE TITLE
Adding new ManyToMany Field in products

### ISSUE THREAD

**Issue by kerwinjorbina** [django-oscar/django-oscar#2683]
I am trying to add a new field in product.

It has similar behavior as the category, but without the parent-child components.

I have successfully added it, but I am having problems on how to show the correct details in the template.

These are the code:

```
class ColorListView(SingleTableView):
    template_name = 'dashboard/catalogue/color_list.html'
    context_object_name = 'colors'
    table_class = ColorTable
    def get_queryset(self):
        table = ColorTable(Color.objects.all())
        return Color.objects.all()`
```
```
class ColorTable(DashboardTable):
    class Meta(DashboardTable.Meta):
        model = Color
        fields = ('name',)
```

I am trying to only show the name column in the table, but all the columns in the model are showing.

![image](https://user-images.githubusercontent.com/4528468/39211809-c65cdec4-47da-11e8-8cfb-dc303e28110f.png)

**Comment by solarissmoke** [comment]
Hi! I'd suggest you post this (and some more details - specifically, the `color_list.html` template - on either the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/django-oscar) or stack overflow, so that someone can help. I am fairly sure the issue is with how you are trying to render it.

I'm closing this issue, as we use Github for bugs and feature requests as opposed to support.
