### ISSUE TITLE
How to import multiple images with same UPC ?

### ISSUE THREAD

**Issue by robbiibadi** [django-oscar/django-oscar#2694]
i just try to populate product with command in django oscar 

sites/sandbox/manage.py oscar_import_catalogue_images sites/sandbox/fixtures/images.tar.gz

and its work, but only for one image in one UPC.

**Comment by solarissmoke** [comment]
I don't think you can. The importer is very much a barebones tool that is intended primarily to get the sandbox site running quickly - if you want to import your own data you will very likely have to extend the built-in importer class to do so.

**Comment by okfish** [comment]
Try to add another gzip file or dir and that images will be attached as secondary

**Comment by robbiibadi** [comment]
what do you mean is in the main zip file there are another zip files?

**Comment by okfish** [comment]
No. Just a few zips images-1.gzip images-2.gzip etc. And pass it one by one to the importing command as parameter15:00, 8 мая 2018 г., robbiibadi <notifications@github.com>:what do you mean is in the main zip file there are another zip files?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by sasha0** [comment]
I believe the topic is already covered, so closing the issue.

In case of new questions/issues, feel free to re-open or create a new one.
