### ISSUE TITLE
Django-Oscar prints email content instead of sending them

### ISSUE THREAD

**Issue by ApsRajput** [django-oscar/django-oscar#2701]
Hello everyone,
I have a issue when I tried sending email forked app, It didn't send and printed instead. Can anyone suggest how to send email.
Thanks

**Comment by solarissmoke** [comment]
Hi - please use the mailing list or slack for support issues - we use Github for bugs and feature requests only. 

In this case, it would appear that you have configured Django to use the [console backend](https://docs.djangoproject.com/en/2.0/topics/email/#console-backend) instead of an SMTP or other backend.
