### ISSUE TITLE
RelatedFieldWidgetWrapper raises KeyError on Django 

### ISSUE THREAD

**Issue by kmetaxas** [django-oscar/django-oscar#2702]
Affects: Django 1.11.0 but not >=1.11.1 (i never tested <1.10. *may* affect early 2.0.)

Problem: Trying to create or view a ProductClass in th Dashboard results in a KeyError on context['field'].

Bug description
-------------------
`RelatedFieldWidgetWrapper` in apps/dashboard/widgets.py: inherits from Widget but does not call super().\_\_init__.  
This means that some variables that `Widget.get_context()` builds are not present in `RelatedFieldWidgetWrapper.get_context()` (context['widget']).

When rendering ProductClass form in the dashboard, the template calls widget_tweaks's `render_field` with a class attribute added. When adding class attributes, widget tweaks will test the `BoundField` for truthyness.
In Django==1.11.0 , `BoundField` is only has \_\_len__ (which is used for truthyness tests) which eventually leads to accessing context['widget'] (which is not created). In later versions (after [this commit](https://github.com/django/django/commit/844ae40a7cdcb1738ca3a2e8f13bb6b8c2e22efd) ) BoundField got a `__bool__()` method so no access to subwidgets happens.

Solution 1: Change `RelatedFieldWidgetWrapper` to call super().\_\_init__. I don't quite understand it entirely and maybe there is a reason it doesn't, so i'm not submitting a PR
Solution 2: Require >Django==1.11.0

**Comment by solarissmoke** [comment]
This is a bug fixed in Django 1.11.1 (https://code.djangoproject.com/ticket/28058). See also https://github.com/jazzband/django-widget-tweaks/issues/44.

> Solution 2: Require >Django==1.11.0

I think our implicit assumption is that projects will follow Django's recommendation of always using the latest minor version. There have been many bug fixes since Django 1.11.0 was released, several of which would affect an Oscar project. 

On that basis my suggestion here would be simply to update your project to the latest version of Django.

**Comment by solarissmoke** [comment]
Can you explain a use case where a field using this widget would implement subwidgets? 

Our `RelatedFieldWidgetWrapper` is basically a copy of [Django's], which also doesn't implement subwidgets (because it is only used for a very specific purpose). I can't see why we would need it to implement it here.

**Comment by solarissmoke** [comment]
Actually, please ignore my previous comment. There is indeed a discrepancy between how our widget handles things and how Django's does. I'm not sure what the correct fix is though - Django's widget doesn't seem to have to override `subwidgets()` and on that basis we shouldn't either.

**Comment by solarissmoke** [comment]
So I've just tested on Django's `RelatedFieldWidgetWrapper`, and it too will raise a `KeyError` if you try to call `subwidgets()` on it. The reason simply is that it doesn't make sense to do that - you would only ever call `subwidgets()` on the `widget` that this wrapper is wrapping. 

I don't think there is an issue here - the bug that you originally reported was fixed in Django.

**Comment by kmetaxas** [comment]
Honestly, i can't come up with a use case for `subwidgets()` for this specific `RelatedFieldWidgetWrapper`. 

The only scenario i can imagine is a library (such as widget_tweaks) accessing a method that eventually leads to .subwidgets(). Apart from `Widget.subwidgets()`, these broken methods include `BoundField.subwidgets()` , `BoundField.__iter__()`, `BoundField.__len__()`, and `BoundField.__getitem__()`.

If `RelatedFieldWidgetWrapper` (and inside a BoundField) is safe from such a scenario, then this bug should be closed.

**Comment by solarissmoke** [comment]
I'm going to close this for now. `RelatedFieldWidgetWrapper` is intended only for use in the dashboard and uses a template that would never result in `subwidgets()` being called. The other issue is resolved in Django 1.11.1, for anyone else that hits it.
