### ISSUE TITLE
Not sure it bug when try to apply both non exclusive offer and coupon, it make basket have negative value

### ISSUE THREAD

**Issue by prince-tanapong** [django-oscar/django-oscar#2773]
### Issue Summary
When I try to play around with non exclusive offer, I found out that when I apply both none exclusive offer and coupon in one cart, it make price negative value.

### Steps to Reproduce
1. I set up not exclusive offer look like.
![screen shot 2018-07-20 at 18 36 41](https://user-images.githubusercontent.com/8855366/43000567-24bd2eb4-8c4c-11e8-99fa-527481467805.png)

2. I set up not exclusive voucher look like this
![screen shot 2018-07-20 at 18 36 06](https://user-images.githubusercontent.com/8855366/43000581-36ff48fa-8c4c-11e8-9fbb-ab708fb2a9a5.png)

3. It can apply both of this offer in basket, that make value negative
![screen shot 2018-07-20 at 18 37 38](https://user-images.githubusercontent.com/8855366/43000602-4e1822f0-8c4c-11e8-846c-6e3d172c31a6.png)

I think it should allow only 1 offer? or this is the wrong setup?

### Technical details

* Python version: Python 3.6.5
* Django version: Version: 2.0.7
* Oscar version: Version: 1.6.2

**Comment by sasha0** [comment]
The offer applicator worked correctly, although not sure if who'd control offer limitation - I'd expect that projects implement those limitation on their end, since someone does not allow discounts higher than 10% of the order total etc.

But ultimately, order total would be zero. What do you think @django-oscar/core @django-oscar/api-team ?

**Comment by pjstevns** [comment]
LOL, welcome to my world. This is a 'feature' of combinable (non-exclusive) offers. All line-based benefits are applied on the base-price (before discounts). This was the only way to make the end-result predictable, because independent of ordering. For relative discounts it also matches closest to what clients generally expect, in my experience.

In this case - stacked absolute discounts - there is indeed a case to minimize the line-total after all benefits to zero. That is what I do in my code....

I'm pretty sure basket/abstract_models.py:Line:line_price_excl_tax_incl_discounts and it's excl_tax sibling are where the max(0, N) should be applied.

**Comment by sasha0** [comment]
Alright, now we do not allow negative values for basket totals per 93f343055e5c3958d09e0d1f718087bf998b9fba.
