### ISSUE TITLE
Support forking of third party applications

### ISSUE THREAD

**Issue by sasha0** [django-oscar/django-oscar#2811]
Continuation of discussion - https://github.com/django-oscar/django-oscar/pull/2633#issuecomment-416530866

I propose to allow forking of third party Oscar apps, since we aim to extract promotions out of the Oscar core. Customization of other pluggable apps is not available at the moment as well. We discussed that potentially the app can provide command to fork it - but I don't think package-specific approach is convenient. WDYT @django-oscar/developers ?

**Comment by dfirst** [comment]
Hi @sasha0 
Currently i`m using oscar- *paypal, *stores and promotions where i really miss option to easy fork apps.

Can you provide a link to this discussion "potentially the app can provide command to fork it", because currently im keeping my fork of oscar-stores https://github.com/dfirst/django-oscar-stores/ and the problems i met is: templatetags, locale paths, template paths, static paths.
I thought about some unified way to solve this problem my idea was is to provide: oscar template loader and static finder but i`m not sure what to do with templatetags.

But anyway it will be good to start from making classes and models loading dynamic in popular 3rd oscar apps.

**Comment by sasha0** [comment]
Tests in the PR #2994 prove that after latest application configs revision (PR #2633) thanks to @jwayodi and @solarissmoke, third-party application fork is now possible, if it uses Oscar-compatible application config.
