### ISSUE TITLE
from oscar import get_core_apps doesn't work

### ISSUE THREAD

**Issue by saitam1** [django-oscar/django-oscar#3014]
### Issue Summary

importing get_core_apps doesn't work. 
`from oscar import get_core_apps` gives me an error:

> ImportError: cannot import name 'get_core_apps' from 'oscar'

### Steps to Reproduce
I am running Python with a virtualenv and have successfully installed the latest version of `oscar` from the master branch via `install.py`.  I can import successfully several other files, which are mentioned in the installation description, e.g.:
```
from oscar.defaults import *
from oscar import OSCAR_MAIN_TEMPLATE_DIR
```
But `from oscar import get_core_apps` throws an error.

### Technical details

* Python version: 3.7.3
* Django version: 2.2.
* Oscar version: 2.0.dev0

**Comment by solarissmoke** [comment]
Hi there. We use Github only for managing bugs and feature requests, and not for support. We recommend that you ask for help on [Stack Overflow](https://stackoverflow.com/) using the `django-oscar` tag, or joining our [slack workspace](https://slack.oscarcommerce.com/) and asking a question there.

(This particular issue is because `get_core_apps` no longer exists in master. see #2633).

**Comment by saitam1** [comment]
Thank you! 
I guess the latest documentation is a bit outdated

**Comment by solarissmoke** [comment]
The documentation on readthedocs is for the latest stable version - you'll need to refer to this repository for documentation changes for unreleased changes (which should be up to date).
