### ISSUE TITLE
Promotions app is still present in 2.0b1 from PyPi

### ISSUE THREAD

**Issue by metsavaht** [django-oscar/django-oscar#3041]
### Issue Summary

Promotions app is still present in `2.0b1`

### Steps to Reproduce

Install `django-oscar==2.0b1` from pypi

Observe that `promotions` app is still present in the installed version.

### Technical details

* Python version: 3.7
* Django version: 2.2.1
* Oscar version: 2.0b1

As I understand this should not be present anymore as it has been extracted to separate repository already.

**Comment by solarissmoke** [comment]
This is odd - thanks for reporting. Will try and make sure that it's removed in the next pre-release.

**Comment by metsavaht** [comment]
Thank you for quick response. Currently working around it by installing from git with `2.0b1` tag.

**Comment by solarissmoke** [comment]
Turns out this is a thing with setuptools - it caches stuff. Leaving a note for myself from the [setuptools documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html):

> NOTE: Due to the way the distutils build process works, a data file that you include in your project and then stop including may be “orphaned” in your project’s build directories, requiring you to run `setup.py clean --all` to fully remove them.

I've added instructions to our release instructions to do this step in future - will be fixed in the next release.

**Comment by solarissmoke** [comment]
This should be fixed in version 2.0. Thanks.
