### ISSUE TITLE
`default_access_fn` always returns True for forked apps

### ISSUE THREAD

**Issue by rik** [django-oscar/django-oscar#3080]
### Issue Summary
I've managed to reproduce this for any dashboard app and will use the Pages dashboard app as the example in this ticket.

I've narrowed the issue down to `apps.get_containing_app_config` returning [Shop](https://github.com/django-oscar/django-oscar/blob/fe983bf7140457d06094d843da0b94ebaea4d6c8/src/oscar/config.py#L13) when it should return `PagesDashboardConfig`.
https://github.com/django-oscar/django-oscar/blob/fe983bf7140457d06094d843da0b94ebaea4d6c8/src/oscar/apps/dashboard/nav.py#L98

I've tried changing the check on line 99 to 
```py
if app_config_instance is None or not isinstance(app_config_instance, OscarDashboardConfig):
```

But then, `get_app_config_class` will return the base `OscarDashboardConfig` class which is also not what we want.

### Steps to Reproduce
1. Fork the Pages dashboard app
`./manage.py oscar_fork_app pages_dashboard . oscar_forks.dashboard.pages`
1. Log into the dashboard with a user with `partner.dashboard_access`
1. Notice the Content submenu is visible while the whole Pages app has this default permission https://github.com/django-oscar/django-oscar/blob/fe983bf7140457d06094d843da0b94ebaea4d6c8/src/oscar/apps/dashboard/pages/apps.py#L13

### Technical details
* Python version: 3.7.4
* Django version: 2.2.3
* Oscar version: 2.0

**Comment by rik** [comment]
I've solved it on my project. I'm not sure if this approach could be generic enough to be used as a basis for a PR.

```py
from functools import lru_cache
from typing import TYPE_CHECKING, Any, Dict, Optional, Sequence, cast

from django.apps import apps
from django.core.exceptions import ImproperlyConfigured
from django.urls import resolve, reverse
from oscar.core.application import OscarDashboardConfig
from oscar.views.decorators import check_permissions

if TYPE_CHECKING:
    from authentication.models import User  # noqa


@lru_cache(maxsize=2)
def _dashboard_urls_to_config() -> Dict[str, OscarDashboardConfig]:
    dashboard_configs = (
        config
        for config in apps.get_app_configs()
        if isinstance(config, OscarDashboardConfig)
    )
    urls_to_config: Dict[str, OscarDashboardConfig] = {}
    for config in dashboard_configs:
        for url in config.urls[0]:
            name = url.pattern.name
            if not name:
                continue

            if name in urls_to_config:
                if urls_to_config[name] != config:
                    raise ImproperlyConfigured(
                        f"'{name}' exists in both {config} and {urls_to_config[name]}! "
                    )

            urls_to_config[url.pattern.name] = config
    return urls_to_config


def default_access_fn(
    user: "User",
    url_name: Optional[str],
    url_args: Optional[Sequence[Any]] = None,
    url_kwargs: Optional[Dict[str, Any]] = None,
) -> bool:
    """
    https://github.com/django-oscar/django-oscar/issues/3080
    """
    if url_name is None:  # it's a heading
        return True

    url = reverse(url_name, args=url_args, kwargs=url_kwargs)
    url_match = resolve(url)
    url_name = cast(str, url_match.url_name)
    app_config_instance = _dashboard_urls_to_config()[url_name]
    permissions = app_config_instance.get_permissions(url_name)

    return check_permissions(user, permissions)
```

**Comment by solarissmoke** [comment]
I think there is a much simpler solution, which is simply not to set a custom `name` on the forked app, and let it inherit the parent class `name`, which is `'oscar.apps.dashboard.pages'`. It should work if you change your forked app's config to just:

    class PagesDashboardConfig(apps.PagesDashboardConfig):
        pass

This will ensure that `get_containing_app_config` returns the correct result, and is actually something we should be enforcing anyway - i.e., that if you fork an oscar app it should have the same name/label as the app you forked.

I think we need to fix the forking command not to set a custom name/label on the forked app.

**Comment by rik** [comment]
I thought of doing this too but this clashes with `default_class_loader` which uses the `app_name` to decide if there is a forked app or not. Maybe `default_class_loader` should change to use `AppConfig.module.__name__.startswith('oscar.apps')` ?

**Comment by solarissmoke** [comment]
I haven't looked at this in enough detail yet, but I believe the issue is with `_find_registered_app_name`, which does this:

    app_label = module_label.split('.')[0]

This means the current class loading behaviour only works for top-level apps such as `catalogue`. It fails with `dashboard.pages` because it ends up returning the `dashboard` app instead of the `dashboard.pages` app.

I think that if we fix this, and then ensure forked apps have the correct `name`, the issue you've raised should be resolved.

**Comment by solarissmoke** [comment]
Some additional notes from my investigations into this:

1. We can't use the same `name` as the core app - this is because of how Django treats the name. In particular the way [it determines the root module for an app is from its `name`](https://github.com/django/django/blob/40c8ffad7249fd37ca1629f06d3ab6b129d84b21/django/apps/config.py#L155-L162). The `name` as currently set by the forking command needs to stay the same. This means the "simple" solution I proposed above to resolve the `default_access_fn` issue will not work.

2. The class loader is fundamentally broken in Oscar 2.0 for any app that is not a top-level oscar app. Overriding a class for something like `catalogue.reviews` or `dashboard.pages` will not work from what I can see.

**Comment by rik** [comment]
> 2\. The class loader is fundamentally broken in Oscar 2.0 for any app that is not a top-level oscar app. Overriding a class for something like `catalogue.reviews` or `dashboard.pages` will not work from what I can see.

This seems to work on my project because I've forked `dashboard` and `dashboard_pages`. For `module == 'dashboard.catalogue.views',  I have `app_name=='oscar_forks.dashboard'` and `local_module_label == 'oscar_forks.dashboard.catalogue.views'`. See how it's doing `module_label.split('.')[1:]` to reconstruct. So if you want to fork a nested app, you need to fork the parent app to make it work.

**Comment by solarissmoke** [comment]
Ah yes, I had forgotten about that requirement. OK, so the only issue is with `default_access_fn`. I think your proposed solution may be the way to go - the call to `get_containing_app_config` needs to be replaced. Grateful if you would be able to make a PR for this!

**Comment by rik** [comment]
Here's my PRs plan:
- [ ] `default_access_fn`
- [ ] Simplify forking command to only override the `name` attribute
- [ ] Document the need to fork top-level apps before nested apps
 Alternatively, we could change the command when forking a nested app to either:
    - warn if the top-level app hasn't been forked yet
    - fork the top-level app if needed
 But to keep things manageable, I'll probably just document for now.

**Comment by solarissmoke** [comment]
The need to fork top-level apps is actually documented in the note here: https://django-oscar.readthedocs.io/en/2.0.0/topics/customisation.html#replace-oscar-s-app-with-your-own-in-installed-apps . The wording could be improved a bit - "should follow overrides" isn't a very explicit way to say that you first need to fork the parent app.

**Comment by solarissmoke** [comment]
Urgh, ignore me, that is a different issue altogether and one that is possibly no longer true.

**Comment by rik** [comment]
So looking into how to write automated tests for this, I'm a bit lost on how to approach it. Any guidance? I'm not going to have a lot of time in the coming days to figure this out.

**Comment by solarissmoke** [comment]
We have a bunch of forked apps in the [`_site` project that is used for tests](https://github.com/django-oscar/django-oscar/tree/master/tests/_site/apps). One approach is to fork one of the dashboard apps into there, and then have integration tests that check that the forked app's config is being used to determine permissions. 

This approach is not particularly pretty because the forking applies for the [entire test suite](https://github.com/django-oscar/django-oscar/blob/0cc99f3bc337d45dfb0341a8ec0345f6ed81f083/tests/settings.py#L73), but we haven't found a better alternative.

This would ideally be in addition to unit tests for `_dashboard_urls_to_config()` for which `get_app_configs()` can be mocked.
