### ISSUE TITLE
 No module named 'apps'

### ISSUE THREAD

**Issue by herbkora** [django-oscar/django-oscar#3227]
Hi, I have used fixtures that come with the sandbox in my project.
When I attempt to add an Item to cart I get this exception

`django.core.exceptions.ImproperlyConfigured: Error importing module apps.offers: No module named 'apps'`

 and this is the exception location

`/venv/lib/python3.6/site-packages/oscar/apps/offer/utils.py in load_proxy, line 30
`
I am using django 2.2.7 and django-oscar 2.0.3

**Comment by solarissmoke** [comment]
The fixtures that come with the sandbox are meant only for use with the sandbox - they will not work in another project. In this case the error you're getting is because the sandbox has defined a [custom benefit](https://github.com/django-oscar/django-oscar/blob/master/sandbox/apps/offers.py#L4), and since this doesn't exist in your project, the fixtures do not load.
