### ISSUE TITLE
wrong loading of models in partner app

### ISSUE THREAD

**Issue by benzkji** [django-oscar/django-oscar#3266]
### Issue Summary

Here: https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/partner/receivers.py#L6

Two models are loaded with `get_classes`, but should this not happen with `get_model`? Using the current approach, I cannot override the `StockRecord` model - using `get_model`, it works without problems? 

Error: RuntimeError: Conflicting 'stockrecord' models in application 'partner': <class 'apps.partner.models.StockRecord'> and <class 'partner.models.StockRecord'>.

Note that I have a running shop, and forked many of the oscar apps, this is the only one not working.

### Steps to Reproduce

Fork partner app, try to override the StockRecord.

### Technical details

This might be my fault...my understanding is, that get_model is for loading models, and get_classes for loading "normal" classes, right?

* Python version: 3.7
* Django version: 1.11
* Oscar version: 1.6 (same code is in 2.0)

**Comment by benzkji** [comment]
my current workaround is to also override the receivers.py, and the ready method in config.py

**Comment by solarissmoke** [comment]
`get_class` isn't semantically right here (it should be `get_model`), but it will still work, as the underlying dynamic loading is the same. 

There is something else wrong - either your forked app label is wrong, or you have included it in `INSTALLED_APPS` directly instead of inside `get_core_apps()`.

Leaving this open as we still need to fix the call to use `get_model`, but your issue is being caused by something else. Please use the mailing list to provide more details if you can't track it down.

**Comment by benzkji** [comment]
wierd, I checked the app label, it's in the same style as the other forked apps. Also, INSTALLED_APPS is correctly setup. Anyway, thanks for clearing up the situation...one day I'll find out ;-)
