### ISSUE TITLE
Migrating forked apps documentation from 1.x to 2.0 is incorrect

### ISSUE THREAD

**Issue by mitchk1609** [django-oscar/django-oscar#3283]
### Issue Summary

The documentation for [migrating forked apps](https://django-oscar.readthedocs.io/en/2.0.4/releases/v2.0.html#migrating-forked-apps) from version 1.x to version 2.0 is incorrect. It states that the `name` attribute of the `AppConfig` subclass in `apps.py` should be renamed to `namespace` but this is not correct and, in fact, doing this means that the forked version of the app is no longer used.

**Comment by jwayodi** [comment]
Did you manage to resolve this, yourself? If not, please let us know what part of your forked app "is no longer used", since you attempted to port to Oscar 2.0. We would need a more detailed explanation, and to see some code (your forked app's `apps` module, and your project's `urls` module), to help you figure out what is wrong.

The `name` attribute of pre-2.0 app configs was used to [pass](https://github.com/django-oscar/django-oscar/blob/releases/1.6/src/oscar/core/application.py#L126) the [URL application namespace](https://docs.djangoproject.com/en/2.2/topics/http/urls/#namespaces-and-include) to including app configs. These app configs could then use it when including the URLs, for example when [calling](https://github.com/django-oscar/django-oscar/blob/releases/1.6/src/oscar/app.py#L29-L63) `django.conf.urls.url()`, as the second item in the three-tuple second argument (similar to what is returned by [`django.urls.conf.include`](https://github.com/django/django/blob/2.2.9/django/urls/conf.py#L54)).

Since version 2.0, Oscar's app configs are extended Django app configs. And since Django's app configs already have an attribute named [`name`](https://docs.djangoproject.com/en/2.2/ref/applications/#django.apps.AppConfig.name), which means something different, the "application namespace" attribute has been renamed to `namespace`.

**Comment by solarissmoke** [comment]
I think we just need to tweak the docs to clarify that `name` now represents the app name as required by Django, and `namespace` is now used to declare the URL namespace for the app.

**Comment by mitchk1609** [comment]
Yes, exactly that @solarissmoke. Apologies if I didn't make that clear enough @jwayodi
