### ISSUE TITLE
Inputs on database design decision

### ISSUE THREAD

**Issue by saiprashanth173** [django-oscar/django-oscar#3292]
Hello folks,

Thanks for developing django-oscar.

We are part of the database group at Georgia Tech. We are developing a tool, called sqlcheck, for assisting database application developers in designing performant and maintainable applications. sqlcheck automatically detects sub-optimal database design choices and suggests better alternatives. For instance, storing comma-separated values in a column violates the first normal form, which impacts the performance, maintainability, and extensibility of the application.

We extracted SQL queries from django-oscar and analysed them with sqlcheck. Here are the results:

- **Too many indexes:** In certain tables (e.g., (ProductAttributeValue src/oscar/apps/catalogue/abstract_models.py (AbstractProductAttributeValue)), (UserAddress, django-oscar/src/oscar/apps/address/abstract_models.py), we observed that the application constructs indexes on almost all of the columns in these models. Our experiments with sqlcheck showed that constructing too many indexes slows down data ingestion. We understand that this design decision could stem from application requirements. Could you please share the rationale behind this design decision?
- **Indexes not being used:** We also found that indexes on certain columns are not being used in the query log obtained by running the integration tests. Is there a reason why you chose to index columns that don’t have any associated filter operations?
- **Usage of floating point values:** We detected the usage Double Precision types for some of your columns (catalogue_product **rating** - src/oscar/apps/catalogue/abstract_models.py, analytics_productrecord **score** - django-oscar/src/oscar/apps/analytics/abstract_models.py). The Float and Double data types are approximate and do not store the exact value, this might lead to inaccurate query results. [Here](https://dev.mysql.com/doc/refman/8.0/en/problems-with-float.html) is a reference to MySQL documentation discussing this. 

We hope that sqlcheck will assist the broader community of database application developers with designing applications. Your feedback will be greatly appreciated.

Thanks for your time.

**Comment by solarissmoke** [comment]
Hi there. We use Github only for managing bugs and feature requests. Broader discussions like this are better suited to our [mailing list](https://groups.google.com/forum/#!forum/django-oscar), and if you have further comments I'd ask that you start a thread there. 

A few short (because of time) responses to the points you raise:

> Too many indexes

Closer inspection of the models in question will make it clear why they have lots of indexes. `ProductAttributeValue` in particular is essentially an EAV model used to store multiple data types, and there can be tens of these per product. It's important to be able to query them efficiently. The cost of slower database ingestion is acceptable in order to achieve this.

> Indexes not being used

There is a flawed underlying assumption in your assessment that if an index wasn't used in the test suite, it isn't necessary. 

Oscar is an extensible e-commerce framework whose purpose is to make it easy for people to build complex applications on top of it. A lot of the database design is intended to facilitate queries that projects built on top of Oscar are likely to want to make. Hard to comment more specifically without seeing which indexes were reported as being unused.

> Usage of floating point values

Both the cases you site are where we store non-critical values. Both `score` and `rating` are (a) calculated averages and (b) approximations intended to provide ranking signals. They don't have to be precise. There is possibly still a discussion to be had about whether a decimal field is more appropriate.
