### ISSUE TITLE
Sandbox dasboard access form broken

### ISSUE THREAD

**Issue by MELindley** [django-oscar/django-oscar#3330]
### Issue Summary

On the form to access the dashboard for the sandbox website ( https://latest.oscarcommerce.com/fr/gateway/)  I get an error after submitting the form, and I never receive the login for the dashboard.

### Steps to Reproduce
Navigate to the dashboard gateway https://latest.oscarcommerce.com/fr/gateway/
Fill in email field and submit form.
Debug output will be shown on screen 

The login information given on launching the website locally works for the sandbox website so I managed to log in that way as a work around :)

**Comment by solarissmoke** [comment]
Yeah, emails are not sent from the Heroku app that now hosts the demo site, and I don't think that is likely to change because sending emails to arbitrary email addresses opens us up to potential abuse - and we have no measures in place to rate-limit/block that. 

We need to remove that gateway form from the sandbox, so that the only way to manage users is through the superuser credentials provided for testing.
