### ISSUE TITLE
Conflicting 'basket_vouchers' models in application 'basket'

### ISSUE THREAD

**Issue by huuquyasb** [django-oscar/django-oscar#3399]
Hi1. I try fork-the-oscar-app basket but  it show error
http://prntscr.com/sxphwj
My code
http://prntscr.com/sxplqr
I tried searching but found no solution
https://django-oscar.readthedocs.io/en/2.0.0/topics/customisation.html#fork-the-oscar-app

Same error:
https://www.mail-archive.com/django-oscar@googlegroups.com/msg00336.html

https://stackoverflow.com/questions/43006599/can-i-use-the-existing-oscar-oscar-api-object-model-to-implement-a-single-item-o

**Comment by solarissmoke** [comment]
Hi there. We use Github only for managing bugs and feature requests, and not for support. We recommend that you ask for help on [Stack Overflow](https://stackoverflow.com/) using the `django-oscar` tag. You will need to provide more information than you have here - in particular the steps you took to fork the app, and the contents of your settings file, as the issue is very likely to be a misconfigured `INSTALLED_APPS` setting. Thanks.

**Comment by huuquyasb** [comment]
Thank you.
I moved "from oscar.apps.basket.models import * " last line  . It worked

http://prntscr.com/sxx08n
