### ISSUE TITLE
Category slug doesn't get updated

### ISSUE THREAD

**Issue by trnc-ck** [django-oscar/django-oscar#3472]
### Issue Summary

When changing the title of a category in the dashboard, the slug doesn't get regenerated.

### Technical details

* Python 3.6.10
* Django version: 2.2.15
* Oscar version: 2.1

**Comment by Andruten** [comment]
I think it's the expected behaviour. If you update the slug it will have a new url and the previous one will raise 404. And it's bad thing for seo.
Maybe could be implemented this feature with django redirects. What do you think @solarissmoke? i could work for that as i implemented this feature in a couple of projects.

**Comment by solarissmoke** [comment]
Oscar doesn't change the slug if it already exists to avoid altering URLs - this was because original the default URLs for category views used only slugs, and altering the slug would break old URLs. Now though, the URLs include the category ID and the view will redirect automatically if the slug portion is wrong, so it would be less problematic to change them. 

That said, I don't think slugs should be updated automatically, and would prefer instead to address #561 - i.e., allow manual editing of slugs. This shouldn't be particularly difficult - just requires exposing the slug field in the dashboard form. PR for this is welcome.
