### ISSUE TITLE
Product's editing price field is not shown in dashboard after forking template

### ISSUE THREAD

**Issue by hungiscoding** [django-oscar/django-oscar#3496]
The price fields where I can edit product wasn't shown in dashboard. After a few days trying to find the bugs, I realized that the dashboard template was not shown correctly for some reason because I forked the whole Oscar template folder to my local machine as in https://django-oscar.readthedocs.io/en/2.1.0/howto/how_to_customise_templates.html (Method 1, I copied the whole templates folder instead of just base.html).

The fix was to delete the dashboard folder in myshop/templates/oscar.

It would be nice to know if this is a bug or there are some other things I need to do if I ever want to customize the dashboard templates? 

Thanks a lot!

**Comment by solarissmoke** [comment]
Hi there. The information you've provided is insufficient to determine whether this is a bug in Oscar or not - deleting your overridden templates suggests that the issue is with your templates rather than with Oscar itself. We would need more information about specifically which templates you copied and what their output was to be able to determine why your forked templates didn't work as expected.

We use Github only for managing bugs and feature requests, and not for support, so if you need further help please open a question on [Stack Overflow](https://stackoverflow.com/) using the `django-oscar` tag, or the [mailing list](https://groups.google.com/forum/#!forum/django-oscar). Thanks.

**Comment by hungiscoding** [comment]
Hi there!

I'm sorry if I wasn't clear in my previous post. The templates folder I copied was the one located in the Oscar framework here: https://github.com/django-oscar/django-oscar/tree/master/src/oscar/templates

What I did was I copied the whole folder above to my shop, which is what I thought I'm suppose to do in order to have full access to Oscar templates and then start editing from there. 

To replicate this problem, you can create a new Oscar project, copy the templates folder above from Oscar (the framework) to the new Oscar project you just created, and adjust the settings.py file so that the local templates files will be serve first (as stated in "Method 1" section) here: https://django-oscar.readthedocs.io/en/2.1.0/howto/how_to_customise_templates.html

The problem was that price field won't appear for editing in Dashboard as in this image: 
![Screen Shot 2020-09-09 at 13 45 57](https://user-images.githubusercontent.com/18361304/92564743-dbd54680-f2a3-11ea-8164-6b297ab8beaf.png)

Please let me know if you need my assistant.
Hung.

**Comment by solarissmoke** [comment]
This looks like a version incompatibility to me - you are using templates taken from a different version of Oscar to what you're running. The `price` field name was changed recently (see #3019) with corresponding changes to the templates, and this is likely what is causing your issue.

**Comment by hungiscoding** [comment]
You are right!

Somehow "pip install django-oscar" install an older version of the framework (?). I reinstalled from git repo and everything seems to work as expected now.

Thanks a lot!
