### ISSUE TITLE
financial settlements

### ISSUE THREAD

**Issue by RasoulRostami** [django-oscar/django-oscar#3537]
hi. where do you handle financial settlements with partners in oscar?
how to you checkout with different partners?

**Comment by solarissmoke** [comment]
Hi there. We use Github only for managing bugs and feature requests, and not for support. We recommend that you ask for help on [Stack Overflow](https://stackoverflow.com/) using the `django-oscar` tag, or joining our [slack workspace](https://slack.oscarcommerce.com/) or [mailing list](https://groups.google.com/forum/#!forum/django-oscar) and asking a question there. Thanks.

**Comment by RasoulRostami** [comment]
but I think it's a bug. there is no way to checkout between partners. if we have multi sellers we can't handle financial settlements with partners

**Comment by solarissmoke** [comment]
@RasoulRostami if you are able to write up in more detail what (a) you are trying to achieve and (b) how you think Oscar should be supporting this, then it is something we'd be able to review and consider. Unfortunately the one-line description you've provided on this issue is not really enough for us to understand either your objectives or where you think there is an issue with Oscar.
