### ISSUE TITLE
metatag block in base.html

### ISSUE THREAD

**Issue by jmarshall9120** [django-oscar/django-oscar#3606]
I've just started with Oscar, am investigating it for a solution.  In my first build I noticed there is no block for meta tags to be overridden/injected into the base.html.  There is also no native keyword tag included there. 

Is this intentional?  

Happy to submit a PR with an added {% block metatags %} if that's desired.

Cheers,

**Comment by solarissmoke** [comment]
hi @jmarshall9120 

The expectation is that you would use the `extrahead` block to insert anything else into the `head` element, including additional meta tags. 

The lack of a `keyword` tag is intentional, in that this tag is ignored by most crawlers, and Oscar's catalogue models by default don't provide for adding keywords to catalogue objects.
