### ISSUE TITLE
static_src and image_not_found.jpg

### ISSUE THREAD

**Issue by jayvdb** [django-oscar/django-oscar#3618]
In oscar 3.0 (beta & master), when image_not_found.jpg is not found, I am getting

> ImproperlyConfigured("Please copy/symlink the 'missing image' image at /path/to/project/public/media/image_not_found.jpg into your MEDIA_ROOT at /path/to/project/public/media. This exception was raised because Oscar was unable to symlink it for you.")

The message is illogical.

Digging around I find my existing symlink is broken, pointing to `/path/to/oscar_repo/../static/oscar/img/image_not_found.jpg` when it should be pointing to `static_src`.

It would be nice if the `MissingProductImage` was able to detect a broken symlink and deletes it before trying to recreate it.

**Comment by solarissmoke** [comment]
> The message is illogical.

Yeah, the first argument to that string is wrong - I'll fix that shortly.

> When it should be pointing to `static_src`.

No, the path it's trying to use is correct - all of `static_src` is copied into `oscar/static` when the build is packaged for PyPi (or if you run `make assets` on a local copy of Oscar, which you need to do to access any of it's static assets).

> It would be nice if the `MissingProductImage` was able to detect a broken symlink and deletes it before trying to recreate it.

I'm not sure that it is a good idea for Oscar to make potentially desctructive changes to the host filesystem - even if the symlink is broken we cannot assume that it used to point to Oscar's image instead of something else. I think we should still just report an exception in this case (and hopefully a corrected exception message will help).
