### ISSUE TITLE
TypeError creating voucher without end-date

### ISSUE THREAD

**Issue by jayvdb** [django-oscar/django-oscar#3619]
In oscar 3.0 beta/master, creating a coupon/voucher , not specifying an end date results in

> TypeError: '>' not supported between instances of 'datetime.datetime' and 'NoneType'

**Comment by solarissmoke** [comment]
Please share the full stack trace for the error, and more detailed steps to reproduce it. 

I'm not able to reproduce this via the dashboard because the form there performs validation to ensure that both start and end date are required, and the `clean()` method on the core voucher models checks that both are set before trying to compare them.

**Comment by solarissmoke** [comment]
Closing due to lack of feedback - feel free to reopen if you can provide more detailed steps to reproduce.

**Comment by jayvdb** [comment]
I am using automated data generators for fuzz testing and also using django admin.

The fact that these fields are required is not defined in the model.  You dont need a backtrace to see that.

**Comment by solarissmoke** [comment]
> You don't need a backtrace to see that.

Please refrain from this sort of unhelpful comment. I asked a simple and reasonable question (for more detailed steps to reproduce). Now that you mentioned you were using the Django admin, it is apparent to me where the issue is, and that it is easily fixed. The model fields do in fact declare both fields as required, and that is not where the problem lies.
