### ISSUE TITLE
Benefit.proxy_class and Condition.proxy_class fields gets overridden if a new offer with a custom condition and benefit is created in the dashboard

### ISSUE THREAD

**Issue by bruecksen** [django-oscar/django-oscar#3662]
I created a custom offer condition and a custom offer benefit according to the documentation (https://django-oscar.readthedocs.io/en/3.0.2/howto/how_to_create_a_custom_condition.html). After the benefit and condition is populated with the create_condition and create_benefit command I wanted to add a new offer with the custom condition and benefit. When I save the new offer in the dashboard both `proxy_class` fields are empty and I get a `Unrecognised condition type ()` error. If I then manually update the fields again, everything works fine.

### Technical details

* Python version: Python 3.8.2
* Django version: Django==2.2.17
* Oscar version: django-oscar==3.0

**Comment by solarissmoke** [comment]
@jwayodi is it possible to fix this in #3632? To reproduce on the sandbox:

1. Start creating an offer and choose the custom incentive (changes customer's name) instead of defining one.
2. Proceed through the other steps and you'll get an error at the final step. 

This happens only on offer creation so the issue is with what is passed through the session during that flow.
