### ISSUE TITLE
Dashboard product list is unusable if an image is missing

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#3735]
### Issue Summary

Thanks for introducing the thumbnailing abstraction. It's something we've always wanted to do! Unfortunately, I think I found a small regression.

On one of my Oscar staging sites, not all images that are in the database are actually on disk. This leads to display errors in the frontend. More importantly, the product list in the dashboard becomes totally unusable, because an exception is thrown.

![image](https://user-images.githubusercontent.com/509427/126622506-97beab8e-9ad8-430a-8612-866f6aad5d33.png)

The exception is thrown if `thumb.height` or `thumb.width` are accessed. And indeed, `product_row_image.html` (the dashboard template) accesses those, and the storefront `gallery.html` doesn't. That's why the storefront only has display errors, but the backend throws an exception.

I wanted to work around this by checking `{% if thumb %}`, but that check always succeeds. My workaround is to remove the height and width section from the template. That template is the only place where `thumb.height` and `width` are accessed.

IIRC, Oscar used to handle this more gracefully. `AbstractProduct.get_missing_image` and the `MissingProductImage` class were introduced back in the days to pass a special hardcoded image through the thumbnailer. I think they're still present, but not used. That way, display errors were avoided.

There are a few ways to fix this. I'm happy to assist, but have not worked on the new thumbnail abstraction, so would like some guidance on what the right fix is. The missing image approach was nice when it worked, but getting the file into the media folder was tricky. So I'm not convinced it's the right approach. What I do know is that accessing a missing image should never keep the site from working.

### Steps to Reproduce

1. Make note of the product PK of the first product with an image in the dashboard product list.
2. Use the Django shell to get the primary key of the `ProductImage` for that product.
3. In the database, change `catalogue_productimage.original` to a non-existent path.
4. Access that product in the frontend, and then in the dashboard product list.

### Technical details

* Python version: 3.8.5
* Django version: 2.2.21
* Oscar version: 2.1.1 (`image_tags.py` and `product_row_image.html` are unchanged on master, so I presume the issue still exists)

**Comment by solarissmoke** [comment]
I am reasonably sure that this only happens when `DEBUG = True`, and that it fails gracefully otherwise. There's also an `OSCAR_THUMBNAIL_DEBUG` setting which can be used to toggle this behaviour independently of `DEBUG`. I think this is consistent with what sorl-thumbnail itself does (`THUMBNAIL_DEBUG`).

I'm not sure what the "correct" behaviour should be when `DEBUG=True` - it does feel like raising an exception is less likely to lead to hard-to-find bugs for a developer?

**Comment by maikhoepfel** [comment]
@solarissmoke Thanks for the prompt reply!

`OSCAR_THUMBNAIL_DEBUG` is one of the first things I tried, because of the code in `image_tags.py`. But I've just verified again, setting `THUMBNAIL_DEBUG` and `OSCAR_THUMBNAIL_DEBUG` to `False` have no effect. And `DEBUG=False` only means I don't get a stacktrace - the exception is still thrown.
I also know that the staging site where this was originally discovered runs with `DEBUG=False`.

**Comment by solarissmoke** [comment]
@maikhoepfel thanks for the clarification and yep, you're right, those settings have no effect. Dug into the `sorl` code to see what's going on, and the issue is [here](https://github.com/jazzband/sorl-thumbnail/blob/29644a4abb727ed57877688027cad156b63dfc32/sorl/thumbnail/base.py#L102-L117). If the source file isn't found, then it just returns a half-baked `ImageFile` object. 

Setting `THUMBNAIL_DUMMY = True` fixes the issue and you don't get an exception, because `DummyImageFile` is returned instead.

This feels to me like a bug in sorl, that should ideally be fixed upstream. It seems a bit weird to return an `ImageFile` that cannot actually be used safely - i.e., an exception should instead be raised there respecting `THUMBNAIL_DEBUG`. If we can't fix it upstream then we need to figure out the best place to handle it here (I'm not sure where that is, since there are no exceptions we can catch - we'd likely have to mess around with the templates).

**Comment by maikhoepfel** [comment]
Ah, great find. I agree with your reasoning, and that this should be discussed with the `sorl` team.

We can still reduce the chance of this happening by not accessing `thumb.height` and `.width` in the offending template. The dashboard product list is the only place where we do this - all other templates don't set the attributes. 
For cleanup, we should also remove the now unused `MissingProductImage` class, `get_missing_image` function, and the `OSCAR_MISSING_IMAGE_URL` setting. If you agree, I'm happy to make a PR.

**Comment by solarissmoke** [comment]
`get_missing_image` is still used, [here](https://github.com/django-oscar/django-oscar/blob/c5e2ac8bb6f018d9b578a160a5d0fd3fe9a1484f/src/oscar/apps/catalogue/abstract_models.py#L713), if a product has no images?

Agree with removing width/height attrs - PR welcome for that!
