### ISSUE TITLE
Docs are wrong

### ISSUE THREAD

**Issue by Bastilla123** [django-oscar/django-oscar#3763]
Found a bug? Please fill out the sections below.

### Issue Summary

https://django-oscar.readthedocs.io/en/3.1/howto/how_to_customise_models.html

i make a local catalogue app. And then insert in models.py:

# yourproject/catalogue/models.py

from django.db import models

from oscar.apps.catalogue.abstract_models import AbstractProduct

class Product(AbstractProduct):
    video_url = models.URLField()

from oscar.apps.catalogue.models import *

i insert in my settings.py in Installed_App:

'catalogue' and then i get a exception that calatalogue Label exists 2 times.

Now i comment:

'oscar.apps.catalogue.apps.CatalogueConfig',

and then i get another exceptions. In older Version from oscar this point works but with 'oscar.apps.catalogue.apps.CatalogueConfig', not further more. Please fix documentation how i can extend products.

### Steps to Reproduce

https://django-oscar.readthedocs.io/en/3.1/howto/how_to_customise_models.html

i make a local catalogue app. And then insert in models.py:

# yourproject/catalogue/models.py

from django.db import models

from oscar.apps.catalogue.abstract_models import AbstractProduct

class Product(AbstractProduct):
    video_url = models.URLField()

from oscar.apps.catalogue.models import *

i insert in my settings.py in Installed_App:

'catalogue' and then i get a exception that calatalogue Label exists 2 times.

Now i comment:

'oscar.apps.catalogue.apps.CatalogueConfig',

and then i get another exceptions. In older Version from oscar this point works but with 'oscar.apps.catalogue.apps.CatalogueConfig', not further more. Please fix documentation how i can extend products.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

* Python version: Run `python --version`.
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
* Oscar version: Look in your requirements.txt, or run `pip show django-oscar | grep Version`.

**Comment by solarissmoke** [comment]
Hi there. We use Github only for managing bugs and feature requests, and not for support. AS you've currently described it, it's not clear to me that this is an issue with the documentation (the instructions provided there for forking an app look fine to me). We would need to see your actual code to help figure out where the issue is for you.

We recommend that you ask for help on [Stack Overflow](https://stackoverflow.com/) using the `django-oscar` tag, or joining our [slack workspace](https://slack.oscarcommerce.com/) or [mailing list](https://groups.google.com/forum/#!forum/django-oscar) and asking a question there. Thanks.
