### ISSUE TITLE
Improve modelling of order communications

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#594]
The 'emails' tab of the dashboard order detail page is blank at the moment.  It should be populated with all emails that have been sent to the customer relating to this order.

The current models don't make this easy.  I think we need to:
- Add an `order` field to the `customer.Email` model - or possibly link the email to the communication event.  Either way, the modelling needs to be altered.

**Comment by sasha0** [comment]
@solarissmoke since we are revising communications in #319, what do you think about David's original idea to add `order` field and display order-related emails in the dashboard?

**Comment by solarissmoke** [comment]
Personally I am not a fan of the "emails" tab - we have had to disable it completely on our sites because it doesn't work at all when you have complex HTML emails (#2317 is heading in the same direction - if we do that then trying to render these emails in the dashboard will be close to impossible). The days of plain text email are (sadly) behind us, and for that reason I would suggest dropping/deprecating this feature in Oscar.

I'm also not sure that it is very useful - why would a user go back to see historic emails in the dashboard (as opposed to just checking their own email client/account)?

**Comment by sasha0** [comment]
> The days of plain text email are (sadly) behind us, and for that reason I would suggest dropping/deprecating this feature in Oscar.

Email tab in the dashboard?

> I'm also not sure that it is very useful - why would a user go back to see historic emails in the dashboard (as opposed to just checking their own email client/account)?

To verify email notification was sent to customer, I suppose.

**Comment by solarissmoke** [comment]
Ah no, I was confusing this with the "Email" section in the customer account view. My mistake.

I'm fine with showing them in the dashboard, although I think you would have to display the raw email body instead of trying to render the HTML (same issue as with the customer account view - it breaks to easily).

**Comment by specialunderwear** [comment]
closing all issues that are no requests that don't have PR's attached.
