### ISSUE TITLE
Extract Application class into a separate library

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#669]
Oscar's `Application` class is quite useful and is already used in several non-Oscar projects.  We should extract it into a separate library so it can be used without requiring all of Oscar.

**Comment by sasha0** [comment]
I didn't attempt to use `Application` outside of the Oscar and I suppose it might be suitable on the projects with the similar design due to the way how it handles URLconfs and permissions.

Although we might reconsider this in the future when `Application` evolves and would be powerful enough as a standalone component.
