### ISSUE TITLE
Better variant product support

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#675]
Variant products have been second class citizens in Oscar for a while and it's time to rectify this.  We need to ensure that products which have variations along one or more dimensions are supported properly with the right data being passed into the template to allow custom widgets to be used.

Example: A T-shirt is available in range of colours and sizes.  We need to be able to support widgets like this one (from gap.com):
![image](https://f.cloud.github.com/assets/80975/511882/80927d84-be11-11e2-9296-161e0333763e.png)

Sometimes all variants will be the same price but sometimes they will be different.  We need to think about how we handle both scenarios.

Related tickets: https://github.com/tangentlabs/django-oscar/issues/481, https://github.com/tangentlabs/django-oscar/issues/379
Related mailing list thread: https://groups.google.com/forum/#!topic/django-oscar/nKVelLiVQmI, https://groups.google.com/forum/?fromgroups=#!topic/django-oscar/PXs6jgdgdWs

**Comment by john-parton** [comment]
I've started some basic work on this.

![screenshot from 2015-01-08 16 09 53](https://cloud.githubusercontent.com/assets/2071543/5671858/f70bea44-9750-11e4-91a0-ec4eb4e96326.png)

Here's some of the interesting bits:

```python
# templatetags.py

def _get_variant_descriptors(product, timeout=DEFAULT_TIMEOUT):
    
    descriptors = {}
    
    for attribute_value in ProductAttributeValue.objects.filter(product=product.children.all()).select_related('product', 'attribute'):
        
        attribute_name, value = attribute_value.attribute.name, attribute_value.value
        
        descriptors.setdefault( attribute_name, {}).setdefault(value, set()).add(attribute_value.product_id)
    
    # In general, we want things sorted when we output them
    return sorted( (attribute, sorted(value_map.items())) for attribute, value_map in descriptors.items() )

@register.inclusion_tag('catalogue/variant_descriptors.html')
def render_variant_descriptors(product):
    return {
        'product': product,
        'descriptors': _get_variant_descriptors(product)
    }
```
Output of `_get_variant_descriptors` looks like this:
```python
[
    (u'Filler', [
        (u'Down Feather', set([26064, 26062])), 
        (u'Poly Fiber', set([26065, 26063]))
    ]), 
    (u'Size', [
        (u'18" x 18"', set([26062, 26063])), 
        (u'22" x 22"', set([26064, 26065]))
    ])
]
```

Variant attribute detection is on a per-product basis and supports arbitrary numbers of dimensions. I'm sure there are lots of edge cases to fix.

```html
<!-- catalogue/variant_descriptors.html -->
{% for attribute, value_map in descriptors %}
<div style="margin-bottom:20px;">
	<h4 class="media-heading">{{ attribute }}</h4>
	<div class="btn-group" data-toggle="buttons-radio">		
		{% for label, ids in value_map %}
			<button type="button" class="btn btn-default" data-product-ids="{{ ids|join:"," }}">{{ label }}</button>
		{% endfor %}
	</div>
</div>
{% endfor %}
```

Need to implement some kind of `VariantDetailView` to display variant-specific information (price, stock, attributevalues, images).

**Comment by john-parton** [comment]
Here's the branch I'm working on: https://github.com/john-parton/django-oscar/tree/issue/675/per_variant_image_support

**Comment by john-parton** [comment]
Here's documentation from Magento on how they handle some of these issues. http://www.magentocommerce.com/knowledge-base/entry/ee1141-ce191-configurable-swatches

There are some screenshots of the backend that might be helpful. 

![Magento example](http://www.magentocommerce.com/images/uploads/configurable_swatches_swap_image_demo.gif)

**Comment by dbrgn** [comment]
@john-parton that looks fantastic! I'm currently working on a shop where we plan to sell 3D prints in different sizes, colors and materials. This change would be perfect for us.

**Comment by dbrgn** [comment]
Another idea: It would be great if some variant dimensions could be managed independently from the products.

Regarding the 3D printing example, we can offer the same colors for all 3D prints. So it's much nicer if we can update the currently available colors in one place instead of updating all products.

**Comment by phedoreanu** [comment]
Something like this: http://beta.dadagraphix.com/catalogue/joker-cat_41/ ?
This is build using django-oscar==0.7.2.

**Comment by john-parton** [comment]
The UI looks pretty good. Is this done in a relatively domain-agnostic way?

**Comment by phedoreanu** [comment]
Yes, I'm using `django.contrib.sites`.

**Comment by john-parton** [comment]
I'm sorry, I didn't mean domain as in the URL. I meant problem domain. http://en.wikipedia.org/wiki/Problem_domain

Does the implementation assume that the dimensions are are colors? For instance, can you swap it out so that the dimensions are "T-shirt size" or "product weight"?

**Comment by phedoreanu** [comment]
No, it's using classic product attributes for size, which is of type "Option" and it gets its values from Catalogue » Attribute Option Groups.
I had no final idea for implementing anything else at the time and I was also waiting for the new official django-oscar releases to see their approach/implementation.

**Comment by unehub** [comment]
Hello, **There are several problems with the current system attributes and variants.**

For example, we sell an iPhone that has multiple colors and multiple ROM .

**Before remember that each variant has a differential stock , they are never equal , so there can be or not a color or not.**

Property
**Colors**: Green, Black
**ROM**: 16GB , 32GB, 64GB , 128GB

**Issue**
Green Color is available in the following ROM: 16GB, 128GB, but not in ['32', '64']
Color Black is available in the following ROM: 16GB , 32GB, 64GB, but not in ['128']

Another example , we sell shirt-T , which has multiple colors and multiple sizes,

Property:
*Colors*: White, Black, Red
*Size* : S , M , L , XL

**Issue**
White available in the following sizes : S, M, but not in ['L', 'XL']
Color Black Available in following the vessel sizes: M, XL, but not in ['S', L']
.....

I think this should be a priority speak this this since 2013 and we have not made any progress in this regard. If someone uncomfortable sorry, the idea is to help, so if the initiative is already working on this subanlo to a branch to collaborate.

**Comment by john-parton** [comment]
You'll need to create a variant for each combination of properties.

In your T-shirt example, you'll need 12 variants: S White, M White, L White, XL White, S Red, M Red, etc.

Each variant should have its own stock record.

This resolves the issue you brought up.

The real issue is that it's tedious for a user to go through a list of 12 variants, and would be much better to select variants by attributes.

**Comment by iraycd** [comment]
Yeah, Shopify and LFS has the similar method. It created MxN. Where M is Varients. N is options.

**Comment by john-parton** [comment]
I've created a few diagrams to aid in discussion.

One issue that I've found is that the placement of attributes can be very confusing. If you're trying to write a query to find all products that have a given attribute value, you have to check on the child as well as on the parent. For instance, if you have one parent, one child, and 3 attribute values, there are actually 8 different ways that they can be configured. Here's 3 of them:

![attribute_issue_1](https://cloud.githubusercontent.com/assets/2071543/10075820/8cd2df70-629d-11e5-8b5d-b7b9f2461dda.png)

Obviously, if you have multiple children, it gets even more complicated.

Because attribute values can be placed on the parent, what does it "mean" when you create a child? Should that child silently "inherit" the attribute values of the parent? Here's a concrete example. Imagine you have a T-shirt that comes in a large, so you create a parent-child relationship with the "Large" attribute value on the parent. Later, you add a medium size as a child, but you leave the "Large" attribute value on the parent. Is that new child implicitly a large size? Does it inherit the attribute value on the parent? Even more confusingly, what if you add a a "Medium" attribute value to the new child? Now you have some potentially conflicting attribute values on both the parent and child.

![attribute_issue_2 1](https://cloud.githubusercontent.com/assets/2071543/10076000/97fc935e-629e-11e5-8130-42de4703e33a.png)

Lastly, a parent-child relationship with a single child is functionally identical to a standalone product. So, you might create a standalone product, only later to realize that you needed to add another variant. So you have to remove the stockrecord, add a child for the old stockrecord, add a new instance of the old stockrecord to the first child, and then you can actually add a new child. This is confusing and error prone.

![attribute_issue_3](https://cloud.githubusercontent.com/assets/2071543/10076096/283f0960-629f-11e5-8438-1171fb017b54.png)

One solution is to remove the concept of a standalone product, and enforce that every product follows the parent-child product. In addition, you move the attribute value relationship to be only on the child, it fixes pretty much all of the attribute value issues.

So that's what I did. Here's my branch: https://github.com/john-parton/django-oscar/tree/issue/675/product_to_parent

This is more than a simple proof of concept. _Every test passes._ (Some had to be tweaked or rewritten, but they're all there.)

On the frontend, it's functionally identical, if not slightly better. For instance, in the old way, if a product is standalone, you can have an "add to cart" button directly under the product. (Neat, that's one fewer step in the funnel.) However, if you had a parent-child relationship with a single child, you don't get that button, even though it's functionally identical to a standalone product. In my new way, you automatically get that button if there's only one child.

The `Product` model has been broken out into two models `Product` and `ChildProduct`. (I would slightly prefer a name like "ProductVariant", but the term "child" is used throughout the code base, so I made it that for consistency.) https://github.com/john-parton/django-oscar/blob/issue/675/product_to_parent/src/oscar/apps/catalogue/abstract_models.py#L241-L593

If you look at the `clean` methods for the models, you should immediately notice something versus the old way: there really isn't anything to them.

There are caveats, of course (there are always caveats):

* I haven't provided any migrations.
* If a overrode the product app, things will probably break.
* If a user has a custom model with a relation to `Product`, it'll probably break.
* Minimal changes were necessary to the templates, but again, there might be some edge cases.

**Comment by taedori81** [comment]
@john-parton How are these things going?
What is recommended way to use your custom abstract_model in catalogue app?

**Comment by john-parton** [comment]
@taedori81 I ended up using a combination of database triggers and custom validation rules to prevent the insertion of standalone products as well as enforcing that all attributes reference child products.  I wouldn't necessarily recommend using the abstract_model unless you're willing to maintain a fork.

**Comment by LennyLip** [comment]
So, if i have 3 product attributes with 5, 4, 10 variants i need to create 200 childs?

**Comment by john-parton** [comment]
If every single combination of those attributes is allowable, then yes. If only certain combinations are allowed, then significantly fewer.

From what I understand, this is pretty similar to most ecommerce solutions: you would need to create 200 "products" and then one "configurable product." (to use magento's terminology)

**Comment by LennyLip** [comment]
@john-parton i have been written such script, so now i have more that 1500 SQL queries (and duplacates) on product page. :)

**Comment by SalahAdDin** [comment]
Until now i see that variant product are handled very good, but haven't enough documentation, i had to search in stack over flow and test some ways and i can now create product variants.

I think that only a good documentation and extern variables missing for the better performances.

By variables i think that a way to get the variant attributes out and can render in templates as we want, as color or sizes.

**Comment by gavve** [comment]
@john-parton  i have followed your code (get_variant_description) and im trying to implement that for a client that wants color and size as button choices as you have. I've added the code you showed in this thread but I can't get it to work quite well. Right now i'm in the middle of writing some jquery hacky stuff to see if the data-option-ids are valid. Each color have a set of ids, for example 1,2,3 and these 3 ids represents what sizes are available for that color. So i'm guessing I could write some javascript that checks if you select a color or size it checks the other sizes and colors and disable/enables them. 

I was wondering how you got this working? Since the code you posted seems like it needs some more work but I can't find your final solution to this problem.

**Comment by albinantony2904** [comment]
I've implemented variant functionality for partners in permission based dashboard.

**Comment by SalahAdDin** [comment]
@albinantony2904 How did you it?

**Comment by mykljohn** [comment]
@albinantony2904 I'd be interested in seeing that as well.

**Comment by ace-han** [comment]
For those people starting `brand-new` project with oscar, I think [Saleor](https://saleor.readthedocs.io/en/latest/architecture/products.html) is giving a good example for variants scenarios.

With below alignments in `django-oscar`
* No more  standalone structures
* `ProductClass`'s attributes starting with `v_` exclusive for `Child` products, other `non-v` attributes for common attributes for all `Parent` products
* `Parent` products only get `non-v` attributes filled
* `Child` products only get `v_` attributes filled 
* Front can build sth similar to @john-parton 's `_get_variant_descriptors` on `v_` attributes only 


![product_class_tree](https://saleor.readthedocs.io/en/latest/_images/product_class_tree.png)

**Comment by sandeepimpressads** [comment]
Anything on this ? It is too long since the issue opened. This functionality is there in most of the ecommerce platforms. We can't tell clients that Oscar doesn't support it as a excuse to not to implement.  :(

**Comment by pjstevns** [comment]
My 2cts,

The whole parent/child nomenclature should go imo. It is a poor/incomplete tree-like implementation with unfortunate semantic connotations.

Grouping of multiple discrete products should not be implemented in a hierarchical model. All products are created equal. If an hierarchy is used, lets please use a real and well supported one, like treebeard.

Grouping of products are generally based on a limited number of traits. Please do not assume that such traits are simply attributes. 

- color is a simple attribute
- material is probably a simple attribute
- weight, size, length etc are definitely *not* simple attributes. The ERP world has this wonderful concept called Unit of Measurement that should be used for such 'composite' traits.

   - weight: UoM { unit: si-gram, quant: 500 }
   - length: UoM { unit: si-meter, quant: 0.65 }
   - size: UoM { unit: US-shoesize, quant: 9 } 

Such UoM types can be enriched with methods to transform them from one unit to another, i.e. US-shoesize <-> EU-shoesize, etc...

How products are grouped is domain-specific, though generally color and size will be sufficient for many if not most use-cases related to e-commerce.

Product-grouping (canonical representations along one or more grouping dimensions) can occur at multiple levels:

considering a product, i.e. a woolen blanket with variations in color, weight/thickness, and size:

- <group>
- <group><color>
- <group><color><weight>
- <group><color><weight><size>

Question is mainly how the 'top-level' grouping is implemented.

The old parent/child setup could be used for that, but as I mentioned, I'm not a fan.

One idea is used by a big enterprise e-commerce solution we also work with:

Assign a single product in a (sub)group as canonical for that level of grouping, and let all variants contain a pointer to that canonical product. Every canonical can point to another 'sibling' to denote a higher grouping level.

Goal should be to have single queries to retrieve all variants at a grouping-level with a single query.

I'll try to come up with a model design....

**Comment by Ajedesign** [comment]
To me this is quite ridiculous that Oscar doesn't support multi-variants, as described in many posts above. This surely must be a massive deal-breaker for many of us trying to run an e-commerce platform?

I have spent many hours/$ setting up Oscar assuming this would definitely not be an issue, all wasted. And now I must find another system with better product support. Does anyone have good suggestions for a new platform?

**Comment by pySilver** [comment]
Side note: That is _ridiculous_ how demanding people are sometime in open source projects. If you are missing feature - make a PR. If you've lost some money because platform does not fit your needs - it's entirely your fault, you simply haven't made a proper research before using a tool. Again, it's an open source project - if you need a feature I believe you can sponsor or develop yourself.

**Comment by trnc-ck** [comment]
Any update on this?

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have open PR's attached.
