### ISSUE TITLE
Translatable models

### ISSUE THREAD

**Issue by maiksprenger** [django-oscar/django-oscar#678]
Currently, several parts of Oscar are not supporting switching languages on-the-fly. Categories are one example. Review is needed to find good solutions to that problem.

**Comment by sasha0** [comment]
@codeinthehole @maikhoepfel what do you think about using https://github.com/deschler/django-modeltranslation?

**Comment by sasha0** [comment]
I'm thinking about integrating `django-modeltranslation`. What do you think @solarissmoke @mvantellingen ?

**Comment by solarissmoke** [comment]
Ok with me, but it would be nice if we could somehow make the dependency optional. Not sure whether that is possible.

**Comment by tobiase** [comment]
I'm not sure if we should use https://github.com/deschler/django-modeltranslation or https://github.com/django-parler/django-parler.
To me django-parler looks like the right approach after reading https://django-parler.readthedocs.io/en/latest/background.html#database-schema, but django-modeltranslation seems to be easier to implement. Could you chime in, @vdboor?

**Comment by pwalsh** [comment]
This was discussed on the mailing list a few years back, but modeltranslation for sure.

**Comment by tobiase** [comment]
I think we should use `django-parler`, because it adds the possibility to add languages without the need to create a migration. With `django-modeltranslation` you have to use a migration, everytime you decide to add a language. `django-parler` adds the possibility to give administrative users using the dashboard more power. It gives us flexibility. If an admin decides to add a language, we could make it possible that they could translate categories, emails, etc. to this language immediately.

**Comment by vdboor** [comment]
(django-parler maintainer here) I've managed to include parler in an oscar website. A somewhat rough implementation is: https://gist.github.com/vdboor/46348490c7cd1a5b08f4  This doesn't properly support tab-switching, but everything else worked with the translated fields. This implementation keeps the old `title` and `description` fields but leaves them alone.

**Comment by denisvlr** [comment]
Looking at @vdboor code, apart from the obvious outdated stuff with django-oscar newer versions (3.0), I ran into issues trying to implement this in a clean way, ie removing the old `title` and `description` fields. 
It seems like it's clashing with the dynamic class loading system: even if the dashboard and dashboard.catalogue apps have correctly been forked and the `ProductClassForm` overridden to remove the original `name` field, it tries to load the original `ProductClassForm` and raises the following error:
```
web_1          |   File "/usr/local/lib/python3.7/site-packages/oscar/apps/dashboard/catalogue/views.py", line 25, in <module>
web_1          |     ('ProductForm',
web_1          |   File "/usr/local/lib/python3.7/site-packages/oscar/core/loading.py", line 48, in get_classes
web_1          |     return class_loader(module_label, classnames, module_prefix)
web_1          |   File "/usr/local/lib/python3.7/site-packages/oscar/core/loading.py", line 106, in default_class_loader
web_1          |     oscar_module = _import_module(oscar_module_label, classnames)
web_1          |   File "/usr/local/lib/python3.7/site-packages/oscar/core/loading.py", line 140, in _import_module
web_1          |     return __import__(module_label, fromlist=classnames)
web_1          |   File "/usr/local/lib/python3.7/site-packages/oscar/apps/dashboard/catalogue/forms.py", line 363, in <module>
web_1          |     class ProductClassForm(forms.ModelForm):
web_1          |   File "/usr/local/lib/python3.7/site-packages/django/forms/models.py", line 266, in __new__
web_1          |     raise FieldError(message)
web_1          | django.core.exceptions.FieldError: Unknown field(s) (name) specified for ProductClass
```
It seems the overridden form is not picked up by other classes importing it.

Also, saving translations don't work with the `Category` model:
```
# override Category
class Category(AbstractCategory, TranslatableModel):
    translations = TranslatedFields(
        tr_name=models.CharField(_("Name"), max_length=255),
        tr_description=models.TextField(_("Description"), blank=True),
    )

# Then:
cat = Category.objects.get(...)
cat.tr_name= "the name"
cat.save() # doesn't raise any exception
cat = Category.objects.get(...)
cat.tr_name

# Raises
# DoesNotExist: Category does not have a translation for the current language!
# Category ID #3, language=en (tried fallbacks en)
# Attempted to read attribute tr_name.
```
I suspect it conflicts with `MP_Node`, since `Category` is the only one inheriting from it.

Does anyone have a working sample code/app with translations for Product, productClass, and Catagory fields?

(Also side note: the Documentation says Django Oscar supports "Multi-lingual products and categories", which is confusing since it's not really supported out of the box).

**Comment by specialunderwear** [comment]
This seems to not be an issue anymore accoring to @movileanuv
