### ISSUE TITLE
Extract analytics app into separate app

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#807]
It really should live outside of Oscar core.

**Comment by sasha0** [comment]
Right now I do not see any good reason to decouple analytics application from the Oscar, since it is tightly integrated into the Oscar (models relates to `Product`, it uses dashboard reports etc).

In its current state it does not make sense to make it general purpose analytics application yet also because it's not flexible in terms of backend for collector of analytical data. Ease of customization of the latter is necessary to use alternative storages for the metrics, like key-value databases etc, which are widely used for the this use-case for performance reasons.

Anyhow, we can re-consider it in the future and then create a new task respectively.
