### ISSUE TITLE
Investigate a more flexible way of storing additional order fees

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#997]
For shops that add extra charges to orders (eg a charge to use a particular payment method), there isn't a natural place to store this field.  You could add fields to the order model but this also requires changes to how order totals are calculated.

It might be better to have a new model for additional charges.  This could be used for shipping charges too and would easily extend for other types of charge.

See https://groups.google.com/forum/#!msg/django-oscar/yTiIMtySxY8/DuxBz-_6f_gJ

**Comment by sasha0** [comment]
Since default checkout flow does not implement mechanism of additional fees application, then I believe the model to store them not needed as well, at the moment.

It does make sense firstly to integrate extra fees application process to the order creator, order totals calculator etc, which would allow to customize them and implement necessary logic. Although I'm still not convinced extra fees application is currently necessary in the Oscar core at all - they won't be commonly used in the standard checkout flow and for the custom flows it will anyway need efforts to implement specific logic, alter models etc.

**Comment by sasha0** [comment]
I believe it's rather part of custom checkout flow, than common, which I already outlined in the comment above.

Closing for now, until we decide to integrate full-fledged extra fee application into the checkout flow.
